#!/usr/bin/env python3
"""Apply targeted QA screenshot cleanup entries to source_queue.tsv.

This script is intentionally narrow: it only adds or updates exact runtime
strings observed during manual QA and writes a report for follow-up testing.
"""

from __future__ import annotations

import csv
from collections import OrderedDict, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
QUEUE = ROOT / "translations/source_queue.tsv"
DICTIONARY = ROOT / "patches/xunity_autotranslator/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"
VISIBLE = ROOT / "extracted/visible_strings.tsv"
NEIGHBORHOODS = ROOT / "extracted/untranslated_neighborhood_report.tsv"
VISUAL_CANDIDATES = ROOT / "extracted/visual_cleanup_candidates.tsv"
OUT_REPORT = ROOT / "extracted/observed_qa_cleanup_report.tsv"

QUEUE_FIELDS = [
    "source",
    "context",
    "file",
    "kind",
    "machine_russian",
    "final_russian",
    "status",
    "notes",
]

REPORT_FIELDS = [
    "observed_string",
    "cluster",
    "action",
    "source_location",
    "final_russian",
    "screenshot_context_notes",
    "needs_runtime_log_verification",
]

QA_TRANSLATIONS: "OrderedDict[str, tuple[str, str, str]]" = OrderedDict(
    [
        ("Peckish", ("Голоден", "friend_status_card", "observed friend status card mood/hunger label")),
        ("Unwell", ("Нездоров", "friend_status_card", "observed friend status card health label")),
        ("Stomach's growling", ("Живот урчит", "top_hud_status", "observed player hunger/status line")),
        ("I'm well rested", ("Я выспался", "top_hud_status", "observed player rest/status line")),
        ("I am well rested", ("Я выспался", "top_hud_status", "rest/status exact variant")),
        ("I'm fully rested", ("Я выспался", "top_hud_status", "rest/status exact variant")),
        ("I am fully rested", ("Я выспался", "top_hud_status", "rest/status exact variant")),
        ("I still have energy", ("Сил ещё хватает", "top_hud_status", "shortened observed energy/status line")),
        ("I still have energy!", ("Сил ещё хватает!", "top_hud_status", "energy/status punctuation variant")),
        ("Reach for it?", ("Дотянуться?", "floating_crate_event", "observed floating crate choice")),
        ("Let Row handle it!", ("Пусть Роу", "floating_crate_event", "observed floating crate friend choice")),
        ("Let Row handle it", ("Пусть Роу", "floating_crate_event", "floating crate friend choice punctuation variant")),
        ("Let Frederik handle it!", ("Пусть Фредерик", "floating_crate_event", "shortened floating crate friend choice")),
        ("Let Frederik handle it", ("Пусть Фредерик", "floating_crate_event", "floating crate friend choice punctuation variant")),
        ("Let Laurel handle it!", ("Пусть Лорел", "floating_crate_event", "floating crate friend choice variant")),
        ("Let Laurel handle it", ("Пусть Лорел", "floating_crate_event", "floating crate friend choice punctuation variant")),
        ("Plastic Bottle", ("Бутылка", "fishing_junk_result", "shortened fishing/junk result for layout")),
        ("Useless Trash...", ("Мусор...", "fishing_junk_result", "shortened fishing/junk result for layout")),
        ("Useless trash...", ("Мусор...", "fishing_junk_result", "case variant for fishing/junk result")),
        ("Trash", ("Мусор", "fishing_junk_result", "short fishing/junk label")),
    ]
)

CLUSTER_TERMS = OrderedDict(
    [
        ("friend_status_card", ["Peckish", "Unwell", "Happy", "FriendManageUI", "FriendHud"]),
        ("friend_action_prompts", ["Heal?", "Feed?", "Talk?", "FriendManageUI", "text_use"]),
        ("top_hud_status", ["Stomach", "well rested", "fully rested", "still have energy", "tired", "healthy"]),
        ("floating_crate_event", ["Reach for it", "Let ", "Get the Crate", "crate", "Crate"]),
        ("fishing_result", ["Weight:", "kg", "(+1 Food!)", "Red Snapper", "FishingController"]),
        ("fishing_junk_result", ["Plastic Bottle", "Useless Trash", "Useless trash", "Trash"]),
    ]
)


def load_tsv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def load_queue() -> list[dict[str, str]]:
    rows = load_tsv(QUEUE)
    if not rows:
        raise SystemExit(f"{QUEUE} is empty or missing")
    missing = set(QUEUE_FIELDS) - set(rows[0])
    if missing:
        raise SystemExit(f"{QUEUE} missing required columns: {sorted(missing)}")
    return rows


def write_queue(rows: list[dict[str, str]]) -> None:
    with QUEUE.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=QUEUE_FIELDS, delimiter="\t", lineterminator="\r\n")
        writer.writeheader()
        writer.writerows(rows)


def write_report(rows: list[dict[str, str]]) -> None:
    OUT_REPORT.parent.mkdir(parents=True, exist_ok=True)
    with OUT_REPORT.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=REPORT_FIELDS, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def append_note(existing: str, note: str) -> str:
    if note in existing:
        return existing
    return f"{existing}; {note}" if existing else note


def unescape_xunity(text: str) -> str:
    return text.replace("\\n", "\n").replace("\\r", "\r").replace("\\\\", "\\")


def load_dictionary_sources() -> set[str]:
    sources: set[str] = set()
    if not DICTIONARY.exists():
        return sources
    with DICTIONARY.open("r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.rstrip("\n")
            if not line or line.startswith("#") or "=" not in line:
                continue
            sources.add(unescape_xunity(line.split("=", 1)[0]))
    return sources


def index_locations() -> dict[str, list[str]]:
    locations: dict[str, list[str]] = defaultdict(list)

    for row in load_tsv(VISIBLE):
        source = row.get("source", "")
        if not source:
            continue
        location = (
            f"{row.get('file', '')}:byte {row.get('byte_offset', '')}; "
            f"object_path_id={row.get('object_path_id', '')}; "
            f"gameobject={row.get('gameobject_name', '')}; kind={row.get('kind', '')}"
        )
        locations[source].append(location)

    for row in load_tsv(NEIGHBORHOODS):
        source = row.get("source", "")
        if not source:
            continue
        location = (
            f"neighborhood:{row.get('asset_file', '')}; "
            f"object_path_id={row.get('object_path_id', '')}; "
            f"offset={row.get('offset', '')}; reason={row.get('nearby_reason', '')}"
        )
        locations[source].append(location)

    for row in load_tsv(VISUAL_CANDIDATES):
        source = row.get("source", "")
        if source:
            locations[source].append(f"visual_cleanup_candidates:{row.get('reason', '')}")

    return locations


def queue_context(row: dict[str, str] | None) -> str:
    if not row:
        return ""
    return f"queue:{row.get('file', '')}; kind={row.get('kind', '')}; context={row.get('context', '')}"


def report_location(source: str, locations: dict[str, list[str]], row: dict[str, str] | None) -> str:
    parts = list(dict.fromkeys(locations.get(source, [])))
    context = queue_context(row)
    if context:
        parts.append(context)
    return " | ".join(parts[:4]) if parts else "not found in extracted visible/neighborhood reports"


def apply_qa_rows(rows: list[dict[str, str]], locations: dict[str, list[str]]) -> list[dict[str, str]]:
    by_source: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        by_source[row["source"]].append(row)

    report_rows: list[dict[str, str]] = []
    for source, (final, cluster, note) in QA_TRANSLATIONS.items():
        matches = by_source.get(source, [])
        if matches:
            action = "already_present"
            for row in matches:
                changed = False
                if row["final_russian"] != final:
                    row["final_russian"] = final
                    changed = True
                if row["status"] != "approved":
                    row["status"] = "approved"
                    changed = True
                new_note = append_note(row["notes"], note)
                if row["notes"] != new_note:
                    row["notes"] = new_note
                    changed = True
                if changed:
                    action = "updated"
            if len(matches) > 1:
                action = f"{action}; duplicate_source_rows={len(matches)}"
            row_for_location = matches[0]
        else:
            row_for_location = {
                "source": source,
                "context": f"observed QA screenshot exact runtime string; cluster={cluster}",
                "file": "manual_runtime",
                "kind": "manual_runtime",
                "machine_russian": "",
                "final_russian": final,
                "status": "approved",
                "notes": note,
            }
            rows.append(row_for_location)
            by_source[source].append(row_for_location)
            action = "added"

        report_rows.append(
            {
                "observed_string": source,
                "cluster": cluster,
                "action": action,
                "source_location": report_location(source, locations, row_for_location),
                "final_russian": final,
                "screenshot_context_notes": note,
                "needs_runtime_log_verification": "yes" if source.startswith("Weight") else "no",
            }
        )

    return report_rows


def source_matches_terms(source: str, row: dict[str, str], terms: list[str]) -> bool:
    haystack = " ".join(
        [
            source,
            row.get("script", ""),
            row.get("gameobject_name", ""),
            row.get("kind", ""),
            row.get("field_path", ""),
            row.get("notes", ""),
        ]
    ).casefold()
    return any(term.casefold() in haystack for term in terms)


def add_cluster_report_rows(
    report_rows: list[dict[str, str]],
    queue_sources: set[str],
    dict_sources: set[str],
    locations: dict[str, list[str]],
) -> None:
    visible_rows = load_tsv(VISIBLE)
    seen: set[tuple[str, str]] = set()
    for cluster, terms in CLUSTER_TERMS.items():
        for row in visible_rows:
            source = row.get("source", "")
            if not source or not source_matches_terms(source, row, terms):
                continue
            key = (cluster, source)
            if key in seen:
                continue
            seen.add(key)
            if source in QA_TRANSLATIONS:
                continue
            if source in queue_sources and source in dict_sources:
                action = "nearby_already_covered"
            elif source in queue_sources:
                action = "nearby_in_queue_only"
            else:
                action = "nearby_candidate_not_added"
            report_rows.append(
                {
                    "observed_string": source,
                    "cluster": cluster,
                    "action": action,
                    "source_location": report_location(source, locations, None),
                    "final_russian": "",
                    "screenshot_context_notes": "nearby same-cluster string; review only, not automatically changed",
                    "needs_runtime_log_verification": "yes" if "Weight:" in source or "kg" in source else "no",
                }
            )


def main() -> int:
    rows = load_queue()
    locations = index_locations()
    report_rows = apply_qa_rows(rows, locations)
    queue_sources = {row["source"] for row in rows}
    dict_sources = load_dictionary_sources()
    add_cluster_report_rows(report_rows, queue_sources, dict_sources, locations)
    write_queue(rows)
    write_report(report_rows)

    added = sum(1 for row in report_rows if row["action"] == "added")
    updated = sum(1 for row in report_rows if row["action"].startswith("updated"))
    nearby = sum(1 for row in report_rows if row["action"].startswith("nearby_"))
    print(f"observed QA cleanup complete: {added} added, {updated} updated, {nearby} nearby report rows")
    print(f"wrote {OUT_REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
