#!/usr/bin/env python3
"""Build a grouped v1.1.3 translation workset from inventories and dumps."""

from __future__ import annotations

import argparse
import csv
import re
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/translation_workset_v1_1_3.tsv"
FIELDS = [
    "priority",
    "cluster_id",
    "category",
    "source_text",
    "current_translation",
    "recommended_translation",
    "status",
    "source_location",
    "object_context",
    "neighbouring_strings",
    "where_to_fix",
    "risk",
    "notes",
]
KNOWN_FIXES = [
    {
        "source_text": "RESULT/SEARCH paper title / ПОИСКА overlap",
        "category": "result/search",
        "recommended_translation": "",
        "notes": "Known visual bug: result/search paper title overlaps with ПОИСКА; review layout/text without global UI layout changes.",
    },
    {
        "source_text": "Your search did not yield results.",
        "category": "result/search",
        "recommended_translation": "Ничего не найдено.",
        "notes": "Known wording fix: replace current Поиск ничего... / Поиск ничего не дал.",
    },
    {
        "source_text": "You found",
        "category": "notification",
        "recommended_translation": "Найдено:",
        "notes": "Known wording fix for result/notification prefix.",
    },
    {
        "source_text": "Scuba set was damaged in the process.",
        "category": "notification",
        "recommended_translation": "Акваланг повреждён.",
        "notes": "Known wording fix: shorter and uses ё.",
    },
    {
        "source_text": "Item Broken",
        "category": "notification",
        "recommended_translation": "Предмет сломан",
        "notes": "Known bug: singular Item Broken remains untranslated.",
    },
    {
        "source_text": "Item Found / Items Found clipped left notification",
        "category": "notification",
        "recommended_translation": "",
        "notes": "Known visual bug around Item Found / Найдено пре... clipping; review shorter wording and UI bounds.",
    },
]
WEIGHT_RE = re.compile(r"\b(?:Weight|kg|Food!\)|Red Snapper|Clownfish|Swordfish|Bass|Sardine|Squid)\b", re.I)
REAL_ITEM_NAMES = {
    "Anchor",
    "Bait",
    "Broken Anchor",
    "Broken Compass",
    "Broken Flashlight",
    "Broken Harpoon Gun",
    "Broken Scuba Set",
    "Broken Telescope",
    "Bucket",
    "Can of Worms",
    "Duct Tape",
    "Energy Bar",
    "Fishing Net",
    "Fishnet",
    "Flare Gun",
    "Food",
    "Harpoon Gun",
    "Scuba Set",
    "Torn Fishing Net",
}
INTERNAL_EXACT = {
    "AllVisualItems",
    "FishedInfoHolder",
    "Item",
    "Item Background",
    "Item Checkmark",
    "Item Label",
    "ItemGenerator",
    "ResultsItems",
    "RollFriendSearch",
    "ScubaGoggles",
    "ScubaImage",
    "ScubaSearchHud",
    "SearchAccepted",
    "SearchDenied",
}
OBJECT_ONLY_RE = re.compile(
    r"^(?:bait|ducttape|flaregun|food_fish|hookgun|net|scuba_set|itemImage|mixamorig:[A-Za-z0-9_:. -]+)"
    r"(?: \([0-9]+\))?(?: N)?$"
)
CAMEL_HELPER_RE = re.compile(r"^[a-z]+(?:[A-Z][A-Za-z0-9]*)+$")


def read_tsv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def normalize(text: str) -> str:
    text = text.replace("’", "'").replace("…", "...")
    text = re.sub(r"<[^>]+>", "", text)
    return re.sub(r"\s+", " ", text).strip().casefold()


def unescape_xunity(text: str) -> str:
    return text.replace("\\n", "\n").replace("\\r", "\r").replace("\\\\", "\\")


def parse_xunity(path: Path) -> dict[str, str]:
    rows: dict[str, str] = {}
    if not path.exists():
        return rows
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for raw in handle:
            line = raw.rstrip("\n")
            if not line or line.startswith("#") or "=" not in line or line.startswith(("r:", "sr:")):
                continue
            source, target = line.split("=", 1)
            rows[unescape_xunity(source)] = unescape_xunity(target)
    return rows


def load_translations() -> tuple[dict[str, str], set[str]]:
    translations: dict[str, str] = {}
    sources_in_queue: set[str] = set()
    for row in read_tsv(ROOT / "translations/source_queue.tsv"):
        source = row.get("source", "")
        target = row.get("final_russian", "") or row.get("machine_russian", "")
        if source:
            sources_in_queue.add(source)
        if source and target and row.get("status") != "skip":
            translations[source] = target
    translations.update(parse_xunity(ROOT / "patches/xunity_autotranslator/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"))
    return translations, sources_in_queue


def translation_for(source: str, translations: dict[str, str]) -> str:
    if source in translations:
        return translations[source]
    norm = normalize(source)
    for candidate, target in translations.items():
        if normalize(candidate) == norm:
            return target
    return ""


def load_object_index() -> dict[tuple[str, str], dict[str, str]]:
    rows = read_tsv(ROOT / ".local_dumps/unity_readable/v1_1_3/object_index.tsv")
    result: dict[tuple[str, str], dict[str, str]] = {}
    for row in rows:
        result[(row.get("asset_file", ""), row.get("path_id", ""))] = row
    return result


def source_location(row: dict[str, str]) -> str:
    asset = row.get("asset_file", "")
    path_id = row.get("path_id", "")
    field = row.get("field_path", "")
    if path_id:
        return f"{asset}:path_id={path_id}:{field}"
    return f"{asset}:{field}"


def cluster_id(row: dict[str, str]) -> str:
    asset = row.get("asset_file", "unknown") or "unknown"
    path_id = row.get("path_id", "") or "no_path"
    return f"{asset}:{path_id}"


def object_context(row: dict[str, str], object_index: dict[tuple[str, str], dict[str, str]]) -> str:
    idx = object_index.get((row.get("asset_file", ""), row.get("path_id", "")), {})
    parts = [
        f"type={row.get('object_type', '')}",
        f"name={row.get('object_name', '')}",
        f"script={idx.get('script_name', '')}",
        f"gameobject={idx.get('gameobject_name', '')}",
        f"dump={idx.get('dump_rel_path', '')}",
    ]
    return "; ".join(part for part in parts if not part.endswith("="))


def is_internal_source_text(source: str) -> bool:
    stripped = source.strip()
    if not stripped or stripped in REAL_ITEM_NAMES:
        return False
    if stripped in INTERNAL_EXACT:
        return True
    if OBJECT_ONLY_RE.match(stripped):
        return True
    if stripped.startswith("mixamorig:"):
        return True
    if CAMEL_HELPER_RE.match(stripped) and not re.search(r"\s", stripped):
        return True
    return False


def is_actual_text_field(row: dict[str, str]) -> bool:
    field = row.get("field_path", "")
    if field.endswith(("m_Text", ".m_Text")):
        return True
    return any(part in field for part in ("TextMeshPro", "TMP_Text", ".text", ".Text"))


def workset_priority_status(row: dict[str, str], default_priority: int, default_status: str) -> tuple[int, str]:
    source = row.get("source_text", "")
    if is_internal_source_text(source) and not is_actual_text_field(row):
        return 9, "ignore-technical"
    return default_priority, default_status


def neighbouring(row: dict[str, str]) -> str:
    return " || ".join(part for part in [row.get("context_before", ""), row.get("context_after", "")] if part)


def where_to_fix(source: str, category: str, sources_in_queue: set[str]) -> str:
    if is_internal_source_text(source):
        return "ignore unless runtime evidence shows this helper/object name is displayed"
    if WEIGHT_RE.search(source):
        return "diagnostic only: choose XUnity regex or runtime plugin strategy; do not add exact numeric rows or bare kg"
    if source in sources_in_queue:
        return "translations/source_queue.tsv, then rebuild XUnity dictionary"
    if category in {"event", "dialogue", "ui", "item", "notification", "result/search"}:
        return "add/update source-text entry in translations/source_queue.tsv"
    return "needs context before choosing dictionary/runtime/plugin fix"


def risk_for(row: dict[str, str], source: str) -> str:
    if is_internal_source_text(source):
        return "none: likely internal object/helper name"
    if WEIGHT_RE.search(source):
        return "high: dynamic runtime formatting and false replacement risk"
    if row.get("status") == "suspicious-mapping":
        return "high: serialized location moved between versions"
    if row.get("category") in {"result/search", "notification", "ui"}:
        return "medium: visible layout/clipping risk"
    if row.get("object_type") == "TextAsset":
        return "medium: needs narrative context and speaker/event validation"
    return "low/medium: verify in clean v1.1.3"


def add_row(
    rows: list[dict[str, str]],
    priority: int,
    row: dict[str, str],
    translations: dict[str, str],
    sources_in_queue: set[str],
    object_index: dict[tuple[str, str], dict[str, str]],
    recommended: str = "",
    status: str | None = None,
    notes: str = "",
) -> None:
    source = row.get("source_text", "")
    if not source:
        return
    category = row.get("category", "unknown")
    current = translation_for(source, translations)
    rows.append(
        {
            "priority": str(priority),
            "cluster_id": cluster_id(row),
            "category": category,
            "source_text": source,
            "current_translation": current,
            "recommended_translation": recommended,
            "status": status or ("needs-review" if current else "todo"),
            "source_location": source_location(row),
            "object_context": object_context(row, object_index),
            "neighbouring_strings": neighbouring(row),
            "where_to_fix": where_to_fix(source, category, sources_in_queue),
            "risk": risk_for(row, source),
            "notes": notes or row.get("notes", ""),
        }
    )


def binary_weight_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for row in read_tsv(ROOT / ".local_dumps/binary_strings/v1_1_3/binary_strings.tsv"):
        source = row.get("string", "")
        if not WEIGHT_RE.search(source):
            continue
        rows.append(
            {
                "version": row.get("version", "v1_1_3"),
                "asset_file": row.get("source_file", ""),
                "object_type": "binary_string",
                "path_id": "",
                "object_name": "",
                "field_path": f"{row.get('encoding', '')}@{row.get('offset', '')}",
                "source_text": source,
                "normalized_source_text": row.get("normalized_string", normalize(source)),
                "category": "dynamic/runtime",
                "status": "needs-context",
                "translation_guess": "",
                "context_before": row.get("context_before", ""),
                "context_after": row.get("context_after", ""),
                "notes": "binary string candidate for weight/fishing diagnostic",
            }
        )
    return rows


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=str(OUT))
    args = parser.parse_args()

    translations, sources_in_queue = load_translations()
    object_index = load_object_index()
    inv112 = read_tsv(ROOT / "docs/string_inventory_v1_1_2.tsv")
    inv113 = read_tsv(ROOT / "docs/string_inventory_v1_1_3.tsv")
    untranslated = read_tsv(ROOT / "docs/untranslated_inventory_v1_1_3.tsv")
    mapping = read_tsv(ROOT / "docs/item_mapping_audit_v1_1_3.tsv")
    old_norms = {
        row.get("normalized_source_text", "")
        for row in inv112
        if row.get("version") == "v1.1.2"
    }

    work_rows: list[dict[str, str]] = []
    for known in KNOWN_FIXES:
        current = translation_for(known["source_text"], translations)
        known_status = "done" if known["recommended_translation"] and current == known["recommended_translation"] else "todo"
        fake = {
            "asset_file": "known_visual_ui_bugs",
            "object_type": "manual",
            "path_id": "",
            "object_name": "",
            "field_path": "",
            "source_text": known["source_text"],
            "category": known["category"],
            "status": known_status,
            "notes": known["notes"],
        }
        add_row(
            work_rows,
            1,
            fake,
            translations,
            sources_in_queue,
            object_index,
            recommended=known["recommended_translation"],
            status=known_status,
            notes=known["notes"],
        )

    for row in mapping:
        priority, status = workset_priority_status(row, 2, row.get("status") or "needs-review")
        add_row(work_rows, priority, row, translations, sources_in_queue, object_index, status=status)

    for row in untranslated:
        if row.get("object_type") == "TextAsset" or row.get("category") in {"event", "dialogue"}:
            priority, status = workset_priority_status(row, 3, "needs-review")
            add_row(work_rows, priority, row, translations, sources_in_queue, object_index, status=status)

    for row in inv113:
        if row.get("version") != "v1.1.3":
            continue
        if row.get("normalized_source_text", "") not in old_norms:
            priority, status = workset_priority_status(row, 4, "new-v1.1.3")
            add_row(work_rows, priority, row, translations, sources_in_queue, object_index, status=status)

    for row in untranslated:
        if row.get("category") in {"ui", "item", "notification", "result/search"}:
            priority, status = workset_priority_status(row, 5, "todo")
            add_row(work_rows, priority, row, translations, sources_in_queue, object_index, status=status)

    for row in [*untranslated, *binary_weight_rows()]:
        if WEIGHT_RE.search(row.get("source_text", "")):
            add_row(work_rows, 6, row, translations, sources_in_queue, object_index, status="strategy-needed")

    seen: set[tuple[str, str, str, str]] = set()
    unique: list[dict[str, str]] = []
    for row in sorted(work_rows, key=lambda item: (int(item["priority"]), item["cluster_id"], item["source_text"].casefold())):
        key = (row["priority"], normalize(row["source_text"]), row["source_location"], row["cluster_id"])
        if key in seen:
            continue
        seen.add(key)
        unique.append(row)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS, delimiter="\t")
        writer.writeheader()
        writer.writerows(unique)
    print(f"wrote {len(unique)} rows to {out}")


if __name__ == "__main__":
    main()
