#!/usr/bin/env python3
"""Build block-oriented v1.1.3 UI coverage from audit/workset context."""

from __future__ import annotations

import argparse
import csv
import re
from collections import OrderedDict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/v1_1_3_ui_block_coverage.tsv"
FIELDS = [
    "block",
    "category",
    "source_text",
    "current_translation",
    "recommended_translation",
    "status",
    "source_location",
    "object_context",
    "neighbouring_strings",
    "layout_risk",
    "where_to_fix",
    "notes",
]

RECOMMENDED = {
    "Restore Defaults": "Сбросить",
    "Fast-Forwarding": "Ускорение",
    "(While ON: Press 'F' to Fast-Forward time during the beginning of night events.)": "Если включено: нажмите F, чтобы ускорить начало ночных событий.",
    "Weight:": "Вес:",
    "I don't feel good": "Мне нехорошо",
    "I'm dying...": "Я умираю...",
    "I have some pain": "Мне больно",
    "I'm starving": "Я умираю от голода",
    "Empty...": "Пусто...",
    "Hungry": "Голод",
    "Starving": "Голод",
    "Depressed": "Подавлен",
    "Miserable": "В отчаянии",
    "Bored": "Скучает",
    "Happy": "Счастлив",
    "Row does not feel well...": "Роу нездоровится...",
    "Makes repairing less demanding today.": "Ремонт сегодня проще.",
    "Support?": "Помочь?",
    "Fix by hand": "Починить вручную",
    "Click to Cancel!": "Нажмите, чтобы отменить!",
    "Try skipping the night?": "Попробовать пропустить ночь?",
    "You sleep guarded tonight...": "Сегодня вы спите под охраной...",
    "Send Row Instead?": "Отправить Роу?",
    "... Just wait here.": "... Просто жди здесь.",
    "Starved to death.": "Умер от голода.",
    "Calculated risk.": "Рассчитанный риск.",
    "Row could not make it.": "Роу не выжил.",
    "Captain Whiskers may wander the sea alone.": "Капитан Усатик может скитаться по морю в одиночестве.",
    "Check the back?": "Посмотреть назад?",
    "Item Found": "Найдено",
    "Items Found": "Найдено:",
    "Item Broken": "Сломано",
    "Items Broken": "Сломано",
    "Item Lost": "Потеряно",
    "Items Lost": "Потеряно",
    "Boat Damaged": "Шлюпка",
    "Broken Compass": "Компас сломан",
    "Broken Scuba Set": "Акваланг сломан",
    "Torn Umbrella": "Рваный зонт",
    "Fix with tape!": "Починить скотчем!",
    "Looks reparable!": "Можно починить.",
    "Looks tasty!": "Выглядит вкусно.",
    "Soaked but readable.": "Намокло, но читаемо.",
    "Details are smudged.": "Детали размазаны.",
}

BLOCK_ORDER = [
    "OptionsMenu",
    "MainMenu",
    "HealthStatusHUD",
    "HungerStatusHUD",
    "FriendSupportPanel",
    "ItemTooltip",
    "ItemCard",
    "BrokenItemActionPrompt",
    "SearchResultPaper",
    "LeftNotification",
    "NightEventChoice",
    "NightEventResult",
    "FishingResultCard",
    "EndingStatsScreen",
    "Journal",
    "Dialogue",
    "UnknownNeedsContext",
]


def read_tsv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def unescape_xunity(text: str) -> str:
    return text.replace("\\n", "\n").replace("\\r", "\r").replace("\\\\", "\\")


def parse_xunity(path: Path) -> dict[str, str]:
    rows: dict[str, str] = {}
    if not path.exists():
        return rows
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not raw or raw.startswith("#") or "=" not in raw or raw.startswith(("r:", "sr:")):
            continue
        source, target = raw.split("=", 1)
        rows[unescape_xunity(source)] = unescape_xunity(target)
    return rows


def load_translations() -> dict[str, str]:
    translations: dict[str, str] = {}
    for row in read_tsv(ROOT / "translations/source_queue.tsv"):
        source = row.get("source", "")
        target = row.get("final_russian", "") or row.get("machine_russian", "")
        if source and target and row.get("status") != "skip":
            translations[source] = target
    translations.update(parse_xunity(ROOT / "patches/xunity_autotranslator/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"))
    translations.update(parse_xunity(ROOT / "dist/dswf-rus-patcher/payload/text/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"))
    return translations


def row_source(row: dict[str, str]) -> str:
    return row.get("source_text") or row.get("source") or ""


def source_location(row: dict[str, str]) -> str:
    if row.get("source_location"):
        return row["source_location"]
    asset = row.get("asset_file") or row.get("source_file") or ""
    path_id = row.get("path_id", "")
    field = row.get("field_path") or row.get("offset") or ""
    if path_id:
        return f"{asset}:path_id={path_id}:{field}"
    return f"{asset}:{field}"


def object_context(row: dict[str, str]) -> str:
    if row.get("object_context"):
        return row["object_context"]
    parts = [
        f"type={row.get('object_type', '')}",
        f"name={row.get('object_name', '')}",
        f"category={row.get('category', '') or row.get('category_guess', '')}",
    ]
    return "; ".join(part for part in parts if not part.endswith("="))


def neighbours(row: dict[str, str]) -> str:
    if row.get("neighbouring_strings"):
        return row["neighbouring_strings"]
    return " || ".join(part for part in [row.get("context_before", ""), row.get("context_after", "")] if part)


def block_for(source: str, row: dict[str, str]) -> str:
    context = " ".join([source, source_location(row), object_context(row), neighbours(row)]).casefold()
    if source in {"Restore Defaults", "Fast-Forwarding", "(While ON: Press 'F' to Fast-Forward time during the beginning of night events.)"} or "setting" in context:
        return "OptionsMenu"
    if source in {"I don't feel good", "I'm dying...", "I have some pain"}:
        return "HealthStatusHUD"
    if source in {"I'm starving", "Hungry", "Starving"}:
        return "HungerStatusHUD"
    if source in {"Depressed", "Miserable", "Bored", "Happy", "Row does not feel well...", "Makes repairing less demanding today.", "Support?"} or "friendmanageui" in context:
        return "FriendSupportPanel"
    if source in {"Broken Compass", "Broken Scuba Set", "Torn Umbrella", "Looks reparable!", "Looks tasty!", "Soaked but readable.", "Details are smudged."}:
        return "ItemCard"
    if source in {"Fix by hand", "Fix with tape!", "Click to Cancel!"}:
        return "BrokenItemActionPrompt"
    if source in {"Item Found", "Items Found", "Item Broken", "Items Broken", "Item Lost", "Items Lost", "Boat Damaged"}:
        return "LeftNotification"
    if source in {"Try skipping the night?", "Send Row Instead?", "... Just wait here.", "Check the back?"}:
        return "NightEventChoice"
    if source in {"You sleep guarded tonight..."}:
        return "NightEventResult"
    if source == "Weight:" or "weight:" in context or "fishedvisuals" in context:
        return "FishingResultCard"
    if source in {"Starved to death.", "Calculated risk.", "Row could not make it.", "Captain Whiskers may wander the sea alone."} or "ending" in context:
        return "EndingStatsScreen"
    if "search" in context:
        return "SearchResultPaper"
    if "journal" in context:
        return "Journal"
    if "dialogue" in context or "dialog" in context:
        return "Dialogue"
    if "menu" in context:
        return "MainMenu"
    return "UnknownNeedsContext"


def layout_risk(block: str, source: str, translation: str) -> str:
    if block in {"LeftNotification", "ItemCard", "BrokenItemActionPrompt", "OptionsMenu", "FishingResultCard"}:
        if len(translation) > 28 or len(source) > 40:
            return "high: cramped visible UI"
        return "medium: verify compact fit in runtime"
    if block in {"EndingStatsScreen", "Journal", "Dialogue"}:
        return "medium: verify multiline fit"
    return "low/medium: verify in runtime"


def status_for(source: str, translation: str, recommended: str, row: dict[str, str]) -> str:
    if recommended and translation == recommended:
        return "done"
    if recommended:
        return "todo-high-confidence"
    status = row.get("status", "")
    if status in {"ignore-technical", "raw-fragment-do-not-translate"}:
        return status
    return "needs-context" if not translation else "done"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=str(OUT))
    args = parser.parse_args()

    translations = load_translations()
    dump_index = ROOT / ".local_dumps/unity_readable/v1_1_3/object_index.tsv"
    dump_objects = read_tsv(dump_index)
    if not dump_objects:
        raise SystemExit(f"missing or empty readable Unity dump object index: {dump_index}")

    candidates: OrderedDict[str, dict[str, str]] = OrderedDict()
    for path in [
        ROOT / "docs/v1_1_3_player_facing_english_coverage.tsv",
        ROOT / "docs/translation_workset_v1_1_3.tsv",
        ROOT / "docs/string_inventory_v1_1_3.tsv",
    ]:
        for row in read_tsv(path):
            source = row_source(row)
            if source and source not in candidates:
                candidates[source] = row

    for source in RECOMMENDED:
        candidates.setdefault(source, {"source_text": source, "category": "runtime-screenshot", "notes": "manual runtime screenshot seed"})

    rows: list[dict[str, str]] = []
    for source, row in candidates.items():
        block = block_for(source, row)
        current = translations.get(source, "")
        recommended = RECOMMENDED.get(source, "")
        status = status_for(source, current, recommended, row)
        if block == "UnknownNeedsContext" and status in {"ignore-technical", "raw-fragment-do-not-translate"}:
            continue
        rows.append(
            {
                "block": block,
                "category": row.get("category") or row.get("category_guess") or "unknown",
                "source_text": source,
                "current_translation": current,
                "recommended_translation": recommended,
                "status": status,
                "source_location": source_location(row),
                "object_context": object_context(row),
                "neighbouring_strings": neighbours(row),
                "layout_risk": layout_risk(block, source, current or recommended),
                "where_to_fix": "translations/source_queue.tsv" if recommended else "review block context before source_queue change",
                "notes": row.get("notes", ""),
            }
        )

    order = {block: i for i, block in enumerate(BLOCK_ORDER)}
    rows.sort(key=lambda r: (order.get(r["block"], 999), r["status"], r["source_text"].casefold()))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {len(rows)} rows to {out}; readable_dump_objects={len(dump_objects)}")


if __name__ == "__main__":
    main()
