#!/usr/bin/env python3
"""Build XUnity.AutoTranslator dictionary from translations/source_queue.tsv."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


DEFAULT_QUEUE = Path("translations/source_queue.tsv")
DEFAULT_OUT = Path(
    "patches/xunity_autotranslator/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"
)


def escape_xunity(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\r", "\\r").replace("\n", "\\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--queue", default=str(DEFAULT_QUEUE))
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    args = parser.parse_args()

    queue = Path(args.queue)
    out = Path(args.out)

    rows: list[tuple[str, str]] = []
    seen: set[str] = set()
    with queue.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        required = {"source", "final_russian", "status"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise SystemExit(f"{queue} missing required columns: {sorted(missing)}")
        for row in reader:
            source = row["source"]
            final = row["final_russian"]
            status = row["status"]
            if status == "skip" or not final:
                continue
            if source in seen:
                raise SystemExit(f"duplicate source in queue: {source!r}")
            seen.add(source)
            rows.append((source, final))

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# DontSleepWithTheFishes_v1_1_2 Russian manual translations\n")
        handle.write("# Generated from translations/source_queue.tsv. Keep as UTF-8.\n")
        handle.write("# Runtime path: BepInEx + XUnity.AutoTranslator, manual/offline dictionary.\n")
        for source, final in sorted(rows, key=lambda pair: pair[0].casefold()):
            handle.write(f"{escape_xunity(source)}={escape_xunity(final)}\n")

    print(f"wrote {len(rows)} translations to {out}")


if __name__ == "__main__":
    main()
