#!/usr/bin/env python3
"""Export the Russian translation source queue from extracted Unity strings."""

from __future__ import annotations

import csv
import re
from collections import defaultdict
from pathlib import Path


VISIBLE = Path("extracted/visible_strings.tsv")
EXISTING_DICT = Path(
    "patches/xunity_autotranslator/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"
)
GLOSSARY = Path("translations/glossary.tsv")
OUT = Path("translations/source_queue.tsv")

FIELDNAMES = [
    "source",
    "context",
    "file",
    "kind",
    "machine_russian",
    "final_russian",
    "status",
    "notes",
]

MANUAL_STRINGS = {
    "Food:",
    "Click To Eat",
    "End Day",
    "Journal",
    "Select Difficulty",
    "Selected",
}

PLAYER_SCRIPT_ALLOWLIST = {
    "Assembly-CSharp:CursorInfoMaker",
    "Assembly-CSharp:FishingController",
}

TECH_EXACT = {
    "Normal",
    "Highlighted",
    "Pressed",
    "Disabled",
    "Assembly-CSharp",
    "UnityEngine",
    "Unity.TextMeshPro",
    "Player",
    "FPS Player",
    "Sliding : false | Dashing : false | Flying : false",
    "Speed: 0 | IsGrounded: true | CoyoteTime: 0.5555",
    "kill\ngetfish\nsuperhelp",
}

SKIP_EXACT = {
    "(Development build)",
    "DopplerGhost",
    "v0.0.0",
    "v0.3.5",
}

NEEDS_REVIEW = {
    "Calm",
    "No Harm",
    "Drowning",
    "Kidnapped",
    "True Ending",
    "Good Luck",
    "Touch Hand?",
    "Fish Food",
    "Today i fucked up by goin on a boat tour and it literally just sink onto the bottom of the fucking ocean.\n\nI'm hungry.",
    "Company's Note: <size=70><color=#ffea8c>\"Calculated Risk\"",
}

DEBUG_PATTERNS = (
    "itemgive-itemid",
    "itemremove-itemid",
    "itembreak-itemid",
    "itemfix-itemid",
    "addhappen",
    "dangerset",
    "getfish",
    "superhelp",
    "Assembly-CSharp",
    "UnityEngine.",
    "Unity.TextMeshPro",
)


def escape_xunity(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\r", "\\r").replace("\n", "\\n")


def unescape_xunity(text: str) -> str:
    return text.replace("\\r", "\r").replace("\\n", "\n").replace("\\\\", "\\")


def load_glossary() -> dict[str, str]:
    if not GLOSSARY.exists():
        return {}
    with GLOSSARY.open("r", encoding="utf-8", newline="") as handle:
        return {
            row["source"]: row["russian"]
            for row in csv.DictReader(handle, delimiter="\t")
            if row.get("source") and row.get("russian")
        }


def technical_or_debug(source: str) -> bool:
    if source in SKIP_EXACT:
        return True
    if source in TECH_EXACT:
        return True
    if any(pattern in source for pattern in DEBUG_PATTERNS):
        return True
    if re.fullmatch(r"#[0-9]+", source):
        return True
    if re.fullmatch(r"[+<>!]|\+[0-9]+", source):
        return True
    if all(ch.isdigit() or ch in ".:%xX- " for ch in source):
        return True
    return False


def player_facing_extracted(row: dict[str, str]) -> bool:
    source = row["source"]
    if not source.strip():
        return False
    if row["file"] not in {f"level{i}" for i in range(1, 6)}:
        return False
    if row["kind"] == "tmp_m_text":
        if source == "Selected":
            return False
        return not technical_or_debug(source)
    if row["script"] in PLAYER_SCRIPT_ALLOWLIST:
        if "_" in source and " " not in source:
            return False
        return not technical_or_debug(source)
    return False


def context_for(row: dict[str, str]) -> str:
    parts = [
        f"file={row['file']}",
        f"kind={row['kind']}",
        f"script={row['script']}",
        f"object_path_id={row['object_path_id']}",
    ]
    if row.get("gameobject_name"):
        parts.append(f"gameobject={row['gameobject_name']}")
    if row.get("byte_offset"):
        parts.append(f"offset={row['byte_offset']}")
    return ";".join(parts)


def read_extracted_sources() -> tuple[dict[str, dict[str, set[str]]], dict[str, str]]:
    grouped: dict[str, dict[str, set[str]]] = defaultdict(
        lambda: {"context": set(), "file": set(), "kind": set()}
    )
    skipped: dict[str, str] = {}
    with VISIBLE.open("r", encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            source = row["source"]
            if player_facing_extracted(row):
                grouped[source]["context"].add(context_for(row))
                grouped[source]["file"].add(row["file"])
                grouped[source]["kind"].add(row["kind"])
            elif row["file"] in {f"level{i}" for i in range(1, 6)} and (
                source in TECH_EXACT
                or source in SKIP_EXACT
                or any(pattern in source for pattern in DEBUG_PATTERNS)
            ):
                skipped.setdefault(source, "technical/debug or non-player-facing extraction")
    return grouped, skipped


def load_existing_dictionary_for_sources(sources: set[str]) -> dict[str, str]:
    if not EXISTING_DICT.exists():
        return {}
    escaped_to_source = {escape_xunity(source): source for source in sources}
    sorted_keys = sorted(escaped_to_source, key=len, reverse=True)
    translations: dict[str, str] = {}
    with EXISTING_DICT.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            for escaped in sorted_keys:
                prefix = f"{escaped}="
                if line.startswith(prefix):
                    translations[escaped_to_source[escaped]] = unescape_xunity(line[len(prefix) :])
                    break
    return translations


def main() -> None:
    glossary = load_glossary()
    grouped, skipped = read_extracted_sources()

    for source in MANUAL_STRINGS | set(glossary):
        if source in TECH_EXACT and source not in {"Selected"}:
            continue
        grouped[source]["context"].add("manual=screenshot_or_glossary")
        grouped[source]["file"].add("manual")
        grouped[source]["kind"].add("manual")

    all_sources = set(grouped) | set(skipped)
    existing = load_existing_dictionary_for_sources(all_sources)

    rows: list[dict[str, str]] = []
    for source in sorted(grouped, key=str.casefold):
        final = glossary.get(source) or existing.get(source, "")
        status = "needs_review" if source in NEEDS_REVIEW else "approved"
        notes = ""
        if source in NEEDS_REVIEW:
            notes = "Context-sensitive; verify in game."
        if not final:
            status = "needs_review"
            notes = "Missing seeded translation; translate before dictionary export."
        rows.append(
            {
                "source": source,
                "context": " | ".join(sorted(grouped[source]["context"])),
                "file": ";".join(sorted(grouped[source]["file"])),
                "kind": ";".join(sorted(grouped[source]["kind"])),
                "machine_russian": "",
                "final_russian": final,
                "status": status,
                "notes": notes,
            }
        )

    for source, note in sorted(skipped.items(), key=lambda item: item[0].casefold()):
        if source in grouped:
            continue
        rows.append(
            {
                "source": source,
                "context": "excluded_from_player_facing_queue",
                "file": "extracted/visible_strings.tsv",
                "kind": "skip",
                "machine_russian": "",
                "final_russian": "",
                "status": "skip",
                "notes": note,
            }
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDNAMES, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)

    approved = sum(1 for row in rows if row["status"] == "approved")
    review = sum(1 for row in rows if row["status"] == "needs_review")
    skip = sum(1 for row in rows if row["status"] == "skip")
    print(f"wrote {len(rows)} rows to {OUT}: {approved} approved, {review} needs_review, {skip} skip")


if __name__ == "__main__":
    main()
