#!/usr/bin/env python3
"""Full project text coverage audit for remaining user-facing English.

This script is intentionally report-only. It scans Unity assets, extracted
tables, XUnity runtime output, and the translation queue, then writes focused
candidate reports without modifying translation sources.
"""

from __future__ import annotations

import csv
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "game_original" / "DontSleepWithTheFishes_Data"
QUEUE = ROOT / "translations/source_queue.tsv"
GENERATED_DICT = ROOT / "patches/xunity_autotranslator/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"
RUNTIME_TEXT_DIR = ROOT / "game_runtime_test/BepInEx/Translation/ru/Text"
RUNTIME_LOG = ROOT / "game_runtime_test/BepInEx/LogOutput.log"
RUNTIME_CONFIG = ROOT / "game_runtime_test/BepInEx/config/AutoTranslatorConfig.ini"
VISIBLE_STRINGS = ROOT / "extracted/visible_strings.tsv"
RESOURCE_STRINGS = ROOT / "extracted/resources_dialogue_strings.tsv"
QUALITY_REPORT = ROOT / "extracted/translation_quality_report.tsv"
JOURNAL_FIT_REPORT = ROOT / "extracted/journal_fit_report.tsv"
TEXTURE_INDEX = ROOT / "debug_reports/texture_export/texture_index.tsv"

DEBUG_MD = ROOT / "debug_reports/full_project_text_audit.md"
DEBUG_TSV = ROOT / "debug_reports/full_project_text_audit.tsv"
USER_FACING_TSV = ROOT / "extracted/full_project_user_facing_candidates.tsv"
MISSING_TSV = ROOT / "extracted/missing_translation_candidates.tsv"
BAD_TSV = ROOT / "extracted/bad_translation_suspects.tsv"
TEXTURE_TSV = ROOT / "extracted/texture_text_candidates.tsv"

ASSET_FILES = [
    DATA / "resources.assets",
    DATA / "resources.resource",
    DATA / "sharedassets0.assets",
    DATA / "sharedassets1.assets",
    DATA / "sharedassets2.assets",
    DATA / "sharedassets3.assets",
    DATA / "sharedassets4.assets",
    DATA / "sharedassets5.assets",
    DATA / "globalgamemanagers.assets",
    DATA / "level1",
    DATA / "level2",
    DATA / "level3",
    DATA / "level4",
    DATA / "level5",
]

AUDIT_FIELDS = [
    "source",
    "current_ru",
    "location",
    "kind",
    "context",
    "category",
    "severity",
    "proposed_fix",
    "action",
    "notes",
]

ASCII_RE = re.compile(rb"[ -~]{3,220}")
UTF16_RE = re.compile(rb"(?:[\x20-\x7e]\x00){3,220}")
WEIGHT_RE = re.compile(r"^(?:<b>)?Weight:(?:</b>)? [0-9]+(?:\.[0-9]+)?kg$")
RICH_WEIGHT_RE = re.compile(r"^<b>Weight:</b> [0-9]+(?:\.[0-9]+)?kg$")
FOOD_COMPOSITE_RE = re.compile(r"^[A-Za-z][A-Za-z '’-]+ \(\+[0-9]+ Food!\)$")
PLACEHOLDER_RE = re.compile(r"\{[0-9A-Za-z_:-]+\}|%[sdif]")
TAG_RE = re.compile(r"<[^>]+>")

ENGLISH_WORD_RE = re.compile(
    r"\b(?:"
    r"Accept|Trade|Give|bait|fish|Pick|chest|Stay|awake|Try|fix|take|look|"
    r"Click|Use|Weight|Food|Hand|map|back|Too|Tired|Could|eat|snack|Item|Found|"
    r"Company|Calculated|Risk|Good|Luck|No|Harm|Kidnapped|Drowning|Calm|True|Ending|"
    r"Fish|Condition|Bait|Energy|Health|Hungry|Peckish|Unwell|Happy|Talk|Heal|Feed|"
    r"Sleep|End|Day|Choose|kg|gulls|though|sometime|okay|left|right|settings|resume"
    r")\b",
    re.IGNORECASE,
)

CLUSTER_TERMS = {
    "Condition",
    "Food",
    "Bait",
    "Energy",
    "Health",
    "Hungry",
    "Peckish",
    "Unwell",
    "Happy",
    "Talk",
    "Heal",
    "Feed",
    "Sleep",
    "End Day",
    "Choose an item",
    "Weight",
    "kg",
    "Accept Trade?",
    "Give bait to fish?",
    "Pick up chest?",
    "Stay awake?",
    "Try to fix?",
    "You should take a look.",
}

KNOWN_RUNTIME_ISSUES = {
    "Weight: 0.28kg",
    "Weight: 25.97kg",
    "Squid (+2 Food!)",
    "Sardine (+1 Food!)",
}

KNOWN_TEXTURE_TERMS = {
    "End Day",
    "Journal",
    "JUNK",
    "main menu/title/logo text",
    "Item Found",
}

TECHNICAL_WORDS = {
    "MonoBehaviour",
    "GameObject",
    "Transform",
    "RectTransform",
    "CanvasRenderer",
    "TextMeshProUGUI",
    "TextMeshPro",
    "TMP_FontAsset",
    "SpriteRenderer",
    "MeshRenderer",
    "Material",
    "Shader",
    "UnityEngine",
    "Assembly-CSharp",
    "m_Name",
    "m_Text",
    "Arial",
    "LiberationSans",
}

USER_ACTION_HINTS = (
    "?",
    "!",
    "...",
    "…",
    ":",
    "<br>",
    " ",
)


try:
    import UnityPy  # type: ignore
except Exception:  # pragma: no cover - optional dependency
    UnityPy = None  # type: ignore


@dataclass(frozen=True)
class Candidate:
    source: str
    location: str
    kind: str
    context: str
    method: str


def read_tsv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def unescape_xunity(text: str) -> str:
    return text.replace("\\n", "\n").replace("\\r", "\r").replace("\\\\", "\\")


def escape_xunity(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\r", "\\r").replace("\n", "\\n")


def parse_xunity_file(path: Path, known_sources: set[str] | None = None) -> dict[str, str]:
    rows: dict[str, str] = {}
    if not path.exists():
        return rows
    escaped_sources: list[tuple[str, str]] = []
    if known_sources:
        escaped_sources = sorted(
            ((escape_xunity(source), source) for source in known_sources),
            key=lambda item: len(item[0]),
            reverse=True,
        )
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for raw in handle:
            line = raw.rstrip("\n")
            if not line or line.startswith("#") or "=" not in line:
                continue
            if line.startswith(("r:", "sr:")):
                continue
            matched = False
            for escaped, source in escaped_sources:
                prefix = f"{escaped}="
                if line.startswith(prefix):
                    rows[source] = unescape_xunity(line[len(prefix) :])
                    matched = True
                    break
            if matched:
                continue
            source, target = line.split("=", 1)
            rows[unescape_xunity(source)] = unescape_xunity(target)
    return rows


def load_runtime_dicts(known_sources: set[str]) -> dict[str, str]:
    rows: dict[str, str] = {}
    if not RUNTIME_TEXT_DIR.exists():
        return rows
    for path in sorted(RUNTIME_TEXT_DIR.glob("*.txt")):
        if path.name == "FishingRegex.txt":
            continue
        rows.update(parse_xunity_file(path, known_sources))
    return rows


def has_cyrillic(text: str) -> bool:
    return any("а" <= char.lower() <= "я" or char == "ё" for char in text)


def has_latin(text: str) -> bool:
    return any("A" <= char <= "Z" or "a" <= char <= "z" for char in text)


def normalize(text: str) -> str:
    text = text.replace("’", "'").replace("…", "...")
    text = TAG_RE.sub("", text)
    return re.sub(r"\s+", " ", text).strip().casefold()


def looks_path_or_identifier(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return True
    if re.search(r"[\\/][A-Za-z0-9_. -]+[\\/]", stripped):
        return True
    if re.search(r"\.(dll|assets|resource|resS|png|jpg|shader|mat|prefab|asset)\b", stripped, re.I):
        return True
    if re.fullmatch(r"[A-Fa-f0-9]{12,}", stripped):
        return True
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", stripped) and "_" in stripped:
        return True
    if re.fullmatch(r"[A-Za-z0-9_.:+/-]{1,80}", stripped) and "." in stripped and " " not in stripped:
        return True
    if any(word in stripped for word in TECHNICAL_WORDS):
        return True
    return False


def looks_player_facing(text: str) -> bool:
    stripped = text.strip()
    if len(stripped) < 2 or len(stripped) > 700:
        return False
    if not has_latin(stripped):
        return False
    if looks_path_or_identifier(stripped):
        return False
    if WEIGHT_RE.match(stripped) or FOOD_COMPOSITE_RE.match(stripped):
        return True
    if any(term.casefold() in stripped.casefold() for term in CLUSTER_TERMS):
        return True
    if any(mark in stripped for mark in USER_ACTION_HINTS):
        return True
    words = re.findall(r"[A-Za-z][A-Za-z'’.-]*", stripped)
    return len(words) >= 2


def looks_noisy_raw(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return True
    if stripped.startswith("[") and ("BepInEx" in stripped or "XUnity" in stripped or "Preloader" in stripped):
        return True
    if stripped.startswith('"') and '";"' in stripped:
        return True
    if stripped[0] in set("!#$%&()*+,./:;<=>?@[\\]^_`{|}~"):
        return True
    letters = sum(1 for char in stripped if char.isalpha())
    ascii_letters = sum(1 for char in stripped if "A" <= char <= "Z" or "a" <= char <= "z")
    symbols = sum(1 for char in stripped if not char.isalnum() and not char.isspace())
    if ascii_letters < 2:
        return True
    if letters / max(len(stripped), 1) < 0.28:
        return True
    if symbols / max(len(stripped), 1) > 0.35:
        return True
    if re.search(r"[!\"#$%&'()*+,./:;<=>?@\[\]\\^_`{|}~-]{8,}", stripped):
        return True
    if re.fullmatch(r"[A-Za-z0-9_() -]{1,80}", stripped) and " " not in stripped and stripped not in CLUSTER_TERMS:
        return True
    if re.fullmatch(r"[A-Za-z0-9_() -]{12,80}", stripped) and " " not in stripped:
        return True
    return False


def raw_candidate_interest(text: str) -> bool:
    if looks_noisy_raw(text):
        return False
    if re.search(r"\bkg\b", text, re.I) and "weight" not in text.casefold() and not re.search(r"\d+(?:\.\d+)?kg\b", text, re.I):
        return False
    cluster_hits = [term for term in CLUSTER_TERMS if term.casefold() in text.casefold() and term != "kg"]
    if cluster_hits:
        return True
    if WEIGHT_RE.match(text) or FOOD_COMPOSITE_RE.match(text):
        return True
    words = re.findall(r"[A-Za-z][A-Za-z'’.-]*", text)
    if len(words) >= 3 and any(mark in text for mark in ["?", "!", "...", "…", ":"]):
        return True
    return False


def clean_raw_ui_candidate(text: str) -> bool:
    stripped = text.strip()
    if not stripped or len(stripped) > 90:
        return False
    if stripped[0].isdigit():
        return False
    if "<br>" in stripped or "\n" in stripped or "\r" in stripped:
        return False
    if any(token in stripped for token in [";", "{", "}", "[", "]", "`", "\\", " -> ", "Base Layer", "AnyState"]):
        return False
    if stripped.startswith(("'", '"')) or stripped.endswith(("'", '"')):
        return False
    if not re.fullmatch(r"[A-Za-z0-9А-Яа-яЁё .,!?:'’+()<>/-]+", stripped):
        return False
    word_tokens = re.findall(r"[A-Za-z]{2,}", stripped)
    if not any(len(token) >= 3 and re.search(r"[AEIOUYaeiouy]", token) for token in word_tokens):
        return False
    if re.fullmatch(r"[A-Za-z_]+ ?\([0-9]+\)(?: [A-Z])?", stripped):
        return False
    if re.fullmatch(r"[A-Za-z_]+(?:_[A-Za-z0-9]+)+", stripped):
        return False
    if "?" in stripped or "!" in stripped or "..." in stripped or "…" in stripped:
        return bool(re.search(r"[A-Za-z]{2,}", stripped))
    if stripped in CLUSTER_TERMS:
        return True
    if re.fullmatch(r"(?:I'm|I am|You|We|The|Try|Give|Pick|Stay|Make|Accept|Use|When|If|Your|Sorry)\b.{2,}", stripped):
        return True
    return False


def likely_technical(text: str, kind: str, context: str) -> bool:
    stripped = text.strip()
    if not stripped or not any(ch.isalpha() for ch in stripped):
        return True
    if not TAG_RE.sub("", stripped).strip() and "<" in stripped and ">" in stripped:
        return True
    if kind == "raw_byte_string":
        if not clean_raw_ui_candidate(stripped):
            return True
        if any(token in stripped for token in ["Base Layer", "AnyState", "Entry ->", " -> "]):
            return True
        if stripped.startswith('"') or stripped.endswith('";"') or '";"' in stripped:
            return True
        if re.fullmatch(r"[A-Za-z_]+ ?\([0-9]+\)(?: [A-Z])?", stripped):
            return True
        if re.fullmatch(r"[A-Za-z_]+[#/\\]?", stripped) and stripped not in CLUSTER_TERMS:
            return True
        if re.fullmatch(r"[A-Za-z_]+[0-9]+(?: \([^)]+\))?", stripped):
            return True
        if re.fullmatch(r"[A-Za-z_]+(?:_[A-Za-z0-9]+)+", stripped):
            return True
        if len(stripped) < 5 and stripped not in CLUSTER_TERMS:
            return True
    if kind in {"GameObject_name_context"}:
        return True
    if looks_path_or_identifier(stripped):
        return True
    lowered = f"{kind} {context}".casefold()
    if any(token in lowered for token in ["shader", "material", "fontasset", "mesh", "spriteatlas"]):
        if not looks_player_facing(stripped):
            return True
    return False


def is_bad_translation_suspect(source: str, target: str) -> tuple[bool, str]:
    if not target:
        return False, ""
    if source == target and looks_player_facing(source):
        return True, "target equals source"
    if has_cyrillic(target) and ENGLISH_WORD_RE.search(TAG_RE.sub(" ", target)):
        return True, f"Russian target contains English-looking fragment: {ENGLISH_WORD_RE.search(target).group(0)}"
    if has_cyrillic(target) and re.search(r"\b[BCDEFGHIJKLMNOPQRSTUVWXYZ]-", target):
        return True, "Latin stutter prefix remains in Russian target"
    source_tags = sorted(TAG_RE.findall(source))
    target_tags = sorted(TAG_RE.findall(target))
    if source_tags != target_tags:
        return True, "TMP/rich text tag mismatch"
    return False, ""


def recursive_strings(value: Any, path: str = "") -> Iterable[tuple[str, str]]:
    if isinstance(value, str):
        yield path, value
    elif isinstance(value, dict):
        for key, item in value.items():
            child = f"{path}.{key}" if path else str(key)
            yield from recursive_strings(item, child)
    elif isinstance(value, (list, tuple)):
        for index, item in enumerate(value):
            child = f"{path}[{index}]"
            yield from recursive_strings(item, child)


def safe_obj_name(obj: Any) -> str:
    try:
        data = obj.read()
        return str(getattr(data, "m_Name", "") or "")
    except Exception:
        try:
            tree = obj.read_typetree(check_read=False)
            return str(tree.get("m_Name", "") or "")
        except Exception:
            return ""


def decode_text_asset_payload(data: Any) -> str:
    payload = getattr(data, "m_Script", b"")
    if isinstance(payload, str):
        return payload
    if isinstance(payload, bytes):
        return payload.decode("utf-8", errors="replace")
    return ""


def scan_unity_file(path: Path) -> list[Candidate]:
    if UnityPy is None or not path.exists():
        return []
    rows: list[Candidate] = []
    try:
        env = UnityPy.load(str(path))
    except Exception:
        return rows

    rel = path.relative_to(ROOT)
    for obj in env.objects:
        type_name = obj.type.name
        name = safe_obj_name(obj)
        base_context = f"asset={rel}; type={type_name}; path_id={obj.path_id}; name={name}"
        if type_name in {"Texture2D", "Sprite"} and name:
            rows.append(Candidate(name, str(rel), f"{type_name}_name", base_context, "unitypy_name"))
            continue

        if type_name == "GameObject" and name:
            rows.append(Candidate(name, str(rel), "GameObject_name_context", base_context, "unitypy_name"))
            continue

        try:
            data = obj.read()
        except Exception:
            data = None

        if type_name == "TextAsset" and data is not None:
            payload = decode_text_asset_payload(data)
            if payload:
                for line_no, text in enumerate(iter_payload_lines(payload), 1):
                    rows.append(
                        Candidate(
                            text,
                            str(rel),
                            "TextAsset_payload",
                            f"{base_context}; line={line_no}",
                            "unitypy_textasset",
                        )
                    )

        if type_name in {"MonoBehaviour", "ScriptableObject"} or type_name.startswith("TextMeshPro"):
            try:
                tree = obj.read_typetree(check_read=False)
            except Exception:
                tree = None
            if tree is not None:
                for field_path, text in recursive_strings(tree):
                    rows.append(
                        Candidate(
                            text,
                            str(rel),
                            f"{type_name}_field",
                            f"{base_context}; field={field_path}",
                            "unitypy_typetree",
                        )
                    )
    return rows


def iter_payload_lines(payload: str) -> Iterable[str]:
    seen: set[str] = set()
    for raw in re.split(r"[\r\n]+", payload):
        text = raw.strip()
        if not text:
            continue
        # CSV-like dialogue rows are useful both as whole rows and field values.
        parts = [part.strip() for part in re.split(r"\t|,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)", text)]
        for value in [text, *parts]:
            value = value.strip().strip('"')
            if value and value not in seen:
                seen.add(value)
                yield value


def raw_strings(path: Path) -> list[Candidate]:
    if not path.exists():
        return []
    data = path.read_bytes()
    rel = path.relative_to(ROOT)
    rows: list[Candidate] = []
    for method, regex, decoder in (
        ("raw_ascii", ASCII_RE, lambda raw: raw.decode("utf-8", errors="replace")),
        ("raw_utf16le", UTF16_RE, lambda raw: raw.decode("utf-16le", errors="replace")),
    ):
        hits = 0
        for match in regex.finditer(data):
            text = decoder(match.group(0)).strip()
            if not text or len(text) > 220:
                continue
            if not raw_candidate_interest(text):
                continue
            rows.append(
                Candidate(
                    text,
                    str(rel),
                    "raw_byte_string",
                    f"byte_offset={match.start()}; method={method}",
                    method,
                )
            )
            hits += 1
            if hits >= 1200:
                break
    return rows


def candidates_from_existing_tables() -> list[Candidate]:
    rows: list[Candidate] = []
    for row in read_tsv(VISIBLE_STRINGS):
        rows.append(
            Candidate(
                row.get("source", ""),
                row.get("file", ""),
                row.get("kind", "visible_string"),
                (
                    f"object_path_id={row.get('object_path_id', '')}; "
                    f"script={row.get('script', '')}; gameobject={row.get('gameobject_name', '')}; "
                    f"offset={row.get('byte_offset', '')}"
                ),
                "extracted_visible_strings",
            )
        )
    for row in read_tsv(RESOURCE_STRINGS):
        rows.append(
            Candidate(
                row.get("source", ""),
                row.get("asset_file", ""),
                row.get("object_type", "resource_string"),
                (
                    f"object_name={row.get('object_name', '')}; path_id={row.get('path_id', '')}; "
                    f"field={row.get('field_path', '')}; location={row.get('offset_or_location', '')}"
                ),
                "extracted_resources_dialogue_strings",
            )
        )
    return rows


def candidates_from_runtime(known_sources: set[str]) -> list[Candidate]:
    rows: list[Candidate] = []
    for path in sorted(RUNTIME_TEXT_DIR.glob("*.txt")) if RUNTIME_TEXT_DIR.exists() else []:
        if path.name == "FishingRegex.txt":
            for line_no, raw in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
                if raw.strip() and not raw.startswith("#"):
                    rows.append(Candidate(raw, str(path.relative_to(ROOT)), "xunity_regex_rule", f"line={line_no}", "runtime_xunity_regex"))
            continue
        for source, target in parse_xunity_file(path, known_sources).items():
            if not target or source == target or looks_player_facing(source):
                rows.append(
                    Candidate(
                        source,
                        str(path.relative_to(ROOT)),
                        "runtime_xunity_text",
                        f"target={target[:120]}",
                        "runtime_xunity_dictionary",
                    )
                )

    if RUNTIME_LOG.exists():
        log_text = RUNTIME_LOG.read_text(encoding="utf-8", errors="replace")
        for line_no, line in enumerate(log_text.splitlines(), 1):
            if any(term.casefold() in line.casefold() for term in CLUSTER_TERMS | KNOWN_RUNTIME_ISSUES):
                rows.append(
                    Candidate(
                        line.strip()[:500],
                        str(RUNTIME_LOG.relative_to(ROOT)),
                        "runtime_log_line",
                        f"line={line_no}",
                        "runtime_log",
                    )
                )
    if RUNTIME_CONFIG.exists():
        for line_no, line in enumerate(RUNTIME_CONFIG.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
            if any(key in line for key in ["OutputUntranslatableText", "EnableTextPathLogging", "TextGetterCompatibilityMode", "IgnoreVirtualTextSetterCallingRules"]):
                rows.append(Candidate(line.strip(), str(RUNTIME_CONFIG.relative_to(ROOT)), "runtime_config", f"line={line_no}", "runtime_config"))
    return rows


def candidates_from_texture_index() -> list[Candidate]:
    rows: list[Candidate] = []
    for row in read_tsv(TEXTURE_INDEX):
        name = row.get("name", "")
        if not name:
            continue
        context = (
            f"type={row.get('type', '')}; path_id={row.get('path_id', '')}; "
            f"size={row.get('width', '')}x{row.get('height', '')}; exported={row.get('exported', '')}"
        )
        rows.append(Candidate(name, row.get("asset_file", ""), "exported_texture_name", context, "texture_index"))
    for term in KNOWN_TEXTURE_TERMS:
        rows.append(Candidate(term, "runtime screenshots / texture export", "known_texture_candidate", "", "manual_known_texture_candidate"))
    return rows


def source_queue_maps() -> tuple[dict[str, dict[str, str]], dict[str, str]]:
    rows = read_tsv(QUEUE)
    by_source = {row.get("source", ""): row for row in rows if row.get("source", "")}
    targets = {row.get("source", ""): row.get("final_russian", "") for row in rows if row.get("source", "")}
    return by_source, targets


def classify_candidate(
    cand: Candidate,
    queue_rows: dict[str, dict[str, str]],
    generated: dict[str, str],
    runtime: dict[str, str],
) -> dict[str, str] | None:
    source = cand.source.strip()
    if not source:
        return None
    if cand.kind == "runtime_log_line" and source.startswith("["):
        return make_row(cand, "", "likely_technical", "low", "", "ignore", "runtime infrastructure log line")

    current_ru = ""
    if source in queue_rows:
        current_ru = queue_rows[source].get("final_russian", "")
    elif source in generated:
        current_ru = generated[source]
    elif source in runtime:
        current_ru = runtime[source]

    queue_row = queue_rows.get(source)
    in_generated = source in generated
    in_runtime = source in runtime

    if cand.kind in {"Texture2D_name", "Sprite_name", "exported_texture_name", "known_texture_candidate"}:
        if source in KNOWN_TEXTURE_TERMS or any(term in source.casefold() for term in ["menu", "button", "journal", "diary", "book", "paper", "page", "note", "junk", "title", "logo", "item", "found"]):
            return make_row(cand, current_ru, "likely_texture_only", "medium", "", "texture_redraw", "texture or sprite name/candidate; requires visual confirmation")
            return make_row(cand, current_ru, "likely_technical", "low", "", "ignore", "texture name does not look player-facing")

    if RICH_WEIGHT_RE.match(source):
        return None

    if WEIGHT_RE.match(source) or "Weight:" in source and "kg" in source:
        return make_row(cand, current_ru, "dynamic_runtime", "high", "Вес: X кг", "runtime_test", "do not solve with exact numeric rows; regex/plugin path must be tested")

    if FOOD_COMPOSITE_RE.match(source):
        return make_row(cand, current_ru, "dynamic_runtime", "medium", "", "runtime_test", "composite fish result; exact dictionary may not cover runtime formatting")

    if likely_technical(source, cand.kind, cand.context):
        return make_row(cand, current_ru, "likely_technical", "low", "", "ignore", "technical/internal-looking string")

    if queue_row:
        status = queue_row.get("status", "")
        if status == "skip":
            return make_row(cand, current_ru, "likely_technical", "low", "", "ignore", "queue row is marked skip")
        if not current_ru:
            return make_row(cand, current_ru, "missing_from_queue", "high", "", "fix_source_queue", "queue row has empty final_russian")
        bad, reason = is_bad_translation_suspect(source, current_ru)
        if bad:
            return make_row(cand, current_ru, "bad_translation_suspect", "medium", "", "fix_source_queue", reason)
        if not in_generated and status == "approved":
            return make_row(cand, current_ru, "in_queue_but_not_dictionary", "high", "", "rebuild_dictionary", "approved queue row is absent from generated dictionary")
        if status == "needs_review":
            return make_row(cand, current_ru, "needs_runtime_check", "medium", "", "runtime_test", "queue row still needs review")
        return make_row(cand, current_ru, "translated", "low", "", "ignore", "covered by source_queue/generated dictionary")

    if source in generated:
        bad, reason = is_bad_translation_suspect(source, generated[source])
        if bad:
            return make_row(cand, generated[source], "bad_translation_suspect", "medium", "", "fix_source_queue", reason)
        return make_row(cand, generated[source], "translated", "low", "", "ignore", "covered by generated dictionary")

    if source in runtime:
        return make_row(cand, runtime[source], "needs_runtime_check", "medium", "", "add_to_source_queue", "seen in runtime XUnity files but absent from source queue")

    if looks_player_facing(source):
        severity = "high" if any(term.casefold() in source.casefold() for term in CLUSTER_TERMS) else "medium"
        return make_row(cand, current_ru, "missing_from_queue", severity, "", "add_to_source_queue", "likely player-facing English source not covered")

    return make_row(cand, current_ru, "likely_technical", "low", "", "ignore", "low-confidence/non-player-facing candidate")


def make_row(
    cand: Candidate,
    current_ru: str,
    category: str,
    severity: str,
    proposed_fix: str,
    action: str,
    notes: str,
) -> dict[str, str]:
    return {
        "source": cand.source.strip(),
        "current_ru": current_ru,
        "location": cand.location,
        "kind": cand.kind,
        "context": cand.context,
        "category": category,
        "severity": severity,
        "proposed_fix": proposed_fix,
        "action": action,
        "notes": f"{notes}; method={cand.method}",
    }


def add_queue_quality_rows(rows: list[dict[str, str]], queue_rows: dict[str, dict[str, str]], generated: dict[str, str]) -> None:
    rich_weight_sources = [source for source in queue_rows if RICH_WEIGHT_RE.match(source)]
    if rich_weight_sources:
        rows.append(
            {
                "source": "<b>Weight:</b> Nkg exact range",
                "current_ru": f"{len(rich_weight_sources)} rows",
                "location": "translations/source_queue.tsv",
                "kind": "source_queue_aggregate",
                "context": "rich exact numeric Weight rows remain after plain Weight cleanup",
                "category": "dynamic_runtime",
                "severity": "high",
                "proposed_fix": "remove exact rich Weight range rows after confirming regex/plugin path",
                "action": "fix_source_queue",
                "notes": "do not regenerate numeric Weight ranges",
            }
        )

    for source, row in queue_rows.items():
        target = row.get("final_russian", "")
        status = row.get("status", "")
        if status == "skip":
            continue
        if not target:
            rows.append(make_row(Candidate(source, "translations/source_queue.tsv", row.get("kind", ""), row.get("context", ""), "source_queue"), target, "missing_from_queue", "high", "", "fix_source_queue", "empty final_russian"))
            continue
        if status == "needs_review":
            rows.append(make_row(Candidate(source, "translations/source_queue.tsv", row.get("kind", ""), row.get("context", ""), "source_queue"), target, "needs_runtime_check", "medium", "", "runtime_test", "queue row still needs review"))
        bad, reason = is_bad_translation_suspect(source, target)
        if bad:
            rows.append(make_row(Candidate(source, "translations/source_queue.tsv", row.get("kind", ""), row.get("context", ""), "source_queue"), target, "bad_translation_suspect", "medium", "", "fix_source_queue", reason))
        if status == "approved" and source not in generated:
            rows.append(make_row(Candidate(source, "translations/source_queue.tsv", row.get("kind", ""), row.get("context", ""), "source_queue"), target, "in_queue_but_not_dictionary", "high", "", "rebuild_dictionary", "approved row absent from generated dictionary"))

    for row in read_tsv(QUALITY_REPORT):
        rows.append(
            {
                "source": row.get("source", ""),
                "current_ru": row.get("final_russian", ""),
                "location": "extracted/translation_quality_report.tsv",
                "kind": row.get("kind", ""),
                "context": row.get("context", ""),
                "category": "bad_translation_suspect",
                "severity": "medium",
                "proposed_fix": "",
                "action": "fix_source_queue",
                "notes": f"{row.get('issue_type', '')}: {row.get('evidence', '')}",
            }
        )

    for row in read_tsv(JOURNAL_FIT_REPORT):
        risk = row.get("risk_level", "")
        if risk in {"high", "medium"}:
            rows.append(
                {
                    "source": row.get("source", ""),
                    "current_ru": row.get("final_russian", ""),
                    "location": "extracted/journal_fit_report.tsv",
                    "kind": row.get("kind", ""),
                    "context": f"estimated_total_lines={row.get('estimated_total_lines', '')}; source_length={row.get('source_length', '')}; final_length={row.get('final_length', '')}",
                    "category": "bad_translation_suspect",
                    "severity": "medium" if risk == "high" else "low",
                    "proposed_fix": "",
                    "action": "fix_source_queue",
                    "notes": f"journal layout risk={risk}; {row.get('notes', '')}",
                }
            )


def dedupe_rows(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    priority = {"high": 0, "medium": 1, "low": 2}
    category_priority = {
        "dynamic_runtime": 0,
        "missing_from_queue": 1,
        "in_queue_but_not_dictionary": 2,
        "bad_translation_suspect": 3,
        "needs_runtime_check": 4,
        "likely_texture_only": 5,
        "translated": 6,
        "likely_technical": 7,
    }
    best: dict[tuple[str, str, str], dict[str, str]] = {}
    for row in rows:
        source = row.get("source", "")
        if not source:
            continue
        key = (source, row.get("category", ""), row.get("action", ""))
        existing = best.get(key)
        if existing is None:
            best[key] = row
            continue
        current_rank = (priority.get(row.get("severity", "low"), 9), category_priority.get(row.get("category", ""), 9), len(row.get("context", "")))
        existing_rank = (priority.get(existing.get("severity", "low"), 9), category_priority.get(existing.get("category", ""), 9), len(existing.get("context", "")))
        if current_rank < existing_rank:
            best[key] = row

    filtered = list(best.values())
    filtered.sort(
        key=lambda row: (
            priority.get(row.get("severity", "low"), 9),
            category_priority.get(row.get("category", ""), 9),
            row.get("source", "").casefold(),
        )
    )
    return filtered


def write_tsv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=AUDIT_FIELDS, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def write_markdown(path: Path, rows: list[dict[str, str]], queue_rows: dict[str, dict[str, str]], generated: dict[str, str]) -> None:
    category_counts = Counter(row["category"] for row in rows)
    severity_counts = Counter(row["severity"] for row in rows)
    needs_review = [row for row in queue_rows.values() if row.get("status") == "needs_review"]
    journal_needs = [row for row in needs_review if row.get("kind", "").startswith("resource_textasset_journal")]
    plain_weight_rows = [source for source in queue_rows if source.startswith("Weight: ")]
    rich_weight_rows = [source for source in queue_rows if RICH_WEIGHT_RE.match(source)]
    quality_findings = read_tsv(QUALITY_REPORT)
    journal_findings = read_tsv(JOURNAL_FIT_REPORT)

    def table(title: str, selected: list[dict[str, str]], limit: int = 40) -> list[str]:
        lines = [f"\n## {title}\n", "| source | current ru | location | category | severity | action | notes |", "|---|---|---|---|---|---|---|"]
        for row in selected[:limit]:
            lines.append(
                "| "
                + " | ".join(
                    md_cell(row.get(field, ""))
                    for field in ["source", "current_ru", "location", "category", "severity", "action", "notes"]
                )
                + " |"
            )
        if len(selected) > limit:
            lines.append(f"\n_... {len(selected) - limit} more rows in TSV._")
        return lines

    high_missing = [row for row in rows if row["category"] == "missing_from_queue" and row["severity"] in {"high", "medium"}]
    textures = [row for row in rows if row["category"] == "likely_texture_only"]
    dynamic = [row for row in rows if row["category"] == "dynamic_runtime"]
    bad = [row for row in rows if row["category"] == "bad_translation_suspect"]
    review = [row for row in rows if row["category"] == "needs_runtime_check"]

    lines = [
        "# Full project text audit",
        "",
        "## Current State",
        "",
        f"- active generated translations: {len(generated)}",
        f"- needs_review count: {len(needs_review)}",
        f"- journal needs_review count: {len(journal_needs)}",
        f"- plain Weight rows left: {len(plain_weight_rows)}",
        f"- rich exact Weight rows left: {len(rich_weight_rows)}",
        f"- quality findings count: {len(quality_findings)}",
        f"- journal fit findings count: {len(journal_findings)}",
        f"- audit TSV rows: {len(rows)}",
        "",
        "## Category Counts",
        "",
    ]
    lines.extend(f"- {key}: {value}" for key, value in sorted(category_counts.items()))
    lines.extend(["", "## Severity Counts", ""])
    lines.extend(f"- {key}: {value}" for key, value in sorted(severity_counts.items()))

    lines.extend(
        [
            "",
            "## Summary",
            "",
            "- This is a report-only audit. It does not edit `translations/source_queue.tsv`.",
            "- Plain `Weight: Xkg` rows are still absent, as expected.",
            "- Rich exact `<b>Weight:</b> Xkg` rows are reported separately if present.",
            "- `FishingRegex.txt` remains a runtime hypothesis until the game proves it applies.",
        ]
    )
    lines.extend(table("Top Missing User-Facing Candidates", high_missing))
    lines.extend(table("Dynamic Runtime Issues", dynamic, 30))
    lines.extend(table("Likely Texture-Only Candidates", textures, 30))
    lines.extend(table("Bad Translation Suspects", bad, 60))
    lines.extend(table("Needs Runtime Check", review, 40))
    lines.extend(
        [
            "",
            "## Recommended Next Small Commit",
            "",
            "1. Remove remaining rich exact `<b>Weight:</b> ...kg` rows if approved, then rebuild and validate.",
            "2. Add high-confidence missing event/action strings from `extracted/missing_translation_candidates.tsv`.",
            "3. Fix obvious bad translation suspects from `extracted/bad_translation_suspects.tsv`.",
            "4. Runtime-test `FishingRegex.txt`; if it does not apply, implement a minimal fishing formatter plugin later.",
            "5. Keep texture redraw work separate using the texture export/candidate reports.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def md_cell(text: str) -> str:
    text = re.sub(r"\s+", " ", str(text)).strip()
    text = text.replace("|", "\\|")
    if len(text) > 140:
        text = text[:137] + "..."
    return text


def main() -> int:
    queue_rows, _queue_targets = source_queue_maps()
    known_sources = set(queue_rows)
    generated = parse_xunity_file(GENERATED_DICT, known_sources)
    runtime = load_runtime_dicts(known_sources)

    candidates: list[Candidate] = []
    candidates.extend(candidates_from_existing_tables())
    candidates.extend(candidates_from_runtime(known_sources))
    candidates.extend(candidates_from_texture_index())

    for path in ASSET_FILES:
        candidates.extend(scan_unity_file(path))
        candidates.extend(raw_strings(path))

    audit_rows: list[dict[str, str]] = []
    for cand in candidates:
        row = classify_candidate(cand, queue_rows, generated, runtime)
        if row is not None:
            audit_rows.append(row)

    add_queue_quality_rows(audit_rows, queue_rows, generated)
    audit_rows = dedupe_rows(audit_rows)

    user_facing = [row for row in audit_rows if row["category"] not in {"likely_technical", "translated"}]
    missing = [row for row in audit_rows if row["category"] == "missing_from_queue"]
    bad = [row for row in audit_rows if row["category"] == "bad_translation_suspect"]
    textures = [row for row in audit_rows if row["category"] == "likely_texture_only"]

    write_tsv(DEBUG_TSV, audit_rows)
    write_tsv(USER_FACING_TSV, user_facing)
    write_tsv(MISSING_TSV, missing)
    write_tsv(BAD_TSV, bad)
    write_tsv(TEXTURE_TSV, textures)
    write_markdown(DEBUG_MD, audit_rows, queue_rows, generated)

    print(f"wrote {len(audit_rows)} audit rows to {DEBUG_TSV.relative_to(ROOT)}")
    print(f"wrote {len(user_facing)} user-facing rows to {USER_FACING_TSV.relative_to(ROOT)}")
    print(f"wrote {len(missing)} missing rows to {MISSING_TSV.relative_to(ROOT)}")
    print(f"wrote {len(bad)} bad-translation rows to {BAD_TSV.relative_to(ROOT)}")
    print(f"wrote {len(textures)} texture rows to {TEXTURE_TSV.relative_to(ROOT)}")
    print(f"wrote markdown report to {DEBUG_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
