#!/usr/bin/env python3
"""Extract newly observed English/untranslated runtime strings from XUnity files."""

from __future__ import annotations

import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RUNTIME_DICT = ROOT / "game_runtime_test/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"
LOG = ROOT / "game_runtime_test/BepInEx/LogOutput.log"
ERROR_LOG = ROOT / "game_runtime_test/BepInEx/ErrorLog.log"
OUT = ROOT / "extracted/runtime_untranslated_strings.tsv"

FIELDS = ["source", "proposed_russian", "status", "origin", "log_context", "notes"]

KNOWN_PROPOSALS = {
    "I'm hungry": "Хочу есть",
    "I am hungry": "Хочу есть",
    "Satisfied": "Сыт",
    "Stomach's growling": "Живот урчит",
    "I'm well rested": "Я выспался",
    "I still have energy": "Сил ещё хватает",
    "Bored": "Скучает",
    "Peckish": "Проголодался",
    "Unwell": "Плоховато",
    "Which way?": "Куда?",
    "Left": "Налево",
    "Right": "Направо",
    "Reach for it?": "Дотянуться?",
    "What are you going to do?": "Что делать?",
    "Get the Crate!": "Достать ящик!",
    "Resume": "Дальше",
    "Instant Clicking": "Клик",
    "(Removes the requirement of holding mouse button.)": "Без удержания мыши.",
}

TEXT_RE = re.compile(r"Setting text on '[^']+' to '(.+?)'(?:$|\n)", re.DOTALL)
ASCII_WORD_RE = re.compile(r"[A-Za-z][A-Za-z0-9'’.,!?():;<>/ +\\-]{1,160}")


def has_cyrillic(text: str) -> bool:
    return any("а" <= char.lower() <= "я" or char == "ё" for char in text)


def looks_english(text: str) -> bool:
    stripped = text.strip()
    if not stripped or has_cyrillic(stripped):
        return False
    if len(stripped) > 180:
        return False
    letters = sum(1 for char in stripped if char.isalpha())
    ascii_letters = sum(1 for char in stripped if "A" <= char <= "Z" or "a" <= char <= "z")
    return ascii_letters >= 2 and ascii_letters >= max(2, letters * 0.7)


def unescape_xunity(text: str) -> str:
    return text.replace("\\n", "\n").replace("\\r", "\r").replace("\\\\", "\\")


def add_candidate(rows: dict[str, dict[str, str]], source: str, origin: str, context: str, notes: str) -> None:
    source = source.strip()
    if not looks_english(source):
        return
    if source not in rows:
        rows[source] = {
            "source": source,
            "proposed_russian": KNOWN_PROPOSALS.get(source, ""),
            "status": "candidate",
            "origin": origin,
            "log_context": context[:500],
            "notes": notes,
        }
    else:
        existing = rows[source]
        if origin not in existing["origin"]:
            existing["origin"] = f"{existing['origin']}; {origin}"


def scan_runtime_dictionary(rows: dict[str, dict[str, str]]) -> None:
    if not RUNTIME_DICT.exists():
        return
    with RUNTIME_DICT.open("r", encoding="utf-8", errors="replace") as handle:
        for lineno, raw in enumerate(handle, 1):
            line = raw.rstrip("\n")
            if not line or line.startswith("#") or "=" not in line:
                continue
            source, target = line.split("=", 1)
            source = unescape_xunity(source)
            target = unescape_xunity(target)
            if not target:
                add_candidate(rows, source, "runtime_dictionary_empty_target", f"{RUNTIME_DICT}:{lineno}", "XUnity emitted a source key with no target")
            elif source == target and looks_english(source):
                add_candidate(rows, source, "runtime_dictionary_identity_target", f"{RUNTIME_DICT}:{lineno}", "target equals English source")
            elif looks_english(target):
                add_candidate(rows, source, "runtime_dictionary_english_target", f"{RUNTIME_DICT}:{lineno}", f"English-looking target: {target}")


def scan_log(path: Path, rows: dict[str, dict[str, str]]) -> None:
    if not path.exists() or path.stat().st_size == 0:
        return
    text = path.read_text(encoding="utf-8", errors="replace")
    for match in TEXT_RE.finditer(text):
        value = match.group(1).strip()
        if looks_english(value):
            start = max(0, match.start() - 180)
            end = min(len(text), match.end() + 260)
            add_candidate(rows, value, path.name, text[start:end].replace("\n", "\\n"), "English text was present in a runtime text-setting log entry")
    for lineno, line in enumerate(text.splitlines(), 1):
        lowered = line.lower()
        if "untranslatable" not in lowered and "untranslated" not in lowered:
            continue
        for match in ASCII_WORD_RE.finditer(line):
            add_candidate(rows, match.group(0), path.name, f"{path}:{lineno}: {line}", "line mentions untranslatable/untranslated text")


def write_rows(rows: dict[str, dict[str, str]]) -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        for row in sorted(rows.values(), key=lambda item: item["source"].casefold()):
            writer.writerow(row)


def main() -> int:
    rows: dict[str, dict[str, str]] = {}
    scan_runtime_dictionary(rows)
    scan_log(LOG, rows)
    scan_log(ERROR_LOG, rows)
    write_rows(rows)
    print(f"wrote {len(rows)} runtime candidates to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
