#!/usr/bin/env python3
"""Scan Unity resource assets for dialogue, journal, and known runtime strings."""

from __future__ import annotations

import csv
import re
import struct
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "game_original" / "DontSleepWithTheFishes_Data"
QUEUE_PATH = PROJECT_ROOT / "translations" / "source_queue.tsv"
DICTIONARY_PATH = (
    PROJECT_ROOT
    / "patches/xunity_autotranslator/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"
)
LOG_PATH = PROJECT_ROOT / "game_runtime_test/BepInEx/LogOutput.log"
CONFIG_PATH = PROJECT_ROOT / "game_runtime_test/BepInEx/config/AutoTranslatorConfig.ini"
OUT_TSV = PROJECT_ROOT / "extracted/resources_dialogue_strings.tsv"
OUT_DOC = PROJECT_ROOT / "docs/resources_assets_findings.md"

ASSET_FILES = [
    "resources.assets",
    "resources.resource",
    "level1",
    "level2",
    "level3",
    "level4",
    "level5",
]

KNOWN_STRINGS = [
    "... Why did you choose me?",
    ".. I'm not sold on the idea that all this was a coincidence.",
    "I'm tired a bit",
    "I still have energy",
    "I feel healthy",
    "Well, there goes Dorothy",
    "Row' and I are the only ones left",
    "Row’ and I are the only ones left",
    "Row",
    "Happy",
    "Talk",
    "End Day",
    "Close Journal",
    "Condition:",
    "Food:",
    "Bait:",
]

OUTPUT_COLUMNS = [
    "source",
    "asset_file",
    "object_type",
    "object_name",
    "path_id",
    "field_path",
    "offset_or_location",
    "confidence",
    "notes",
]


try:
    import UnityPy  # type: ignore
except Exception:  # pragma: no cover - optional dependency
    UnityPy = None  # type: ignore


@dataclass
class Finding:
    source: str
    asset_file: str
    object_type: str
    object_name: str
    path_id: str
    field_path: str
    offset_or_location: str
    confidence: str
    notes: str

    def key(self) -> tuple[str, str, str, str, str]:
        return (
            self.source,
            self.asset_file,
            self.object_type,
            self.path_id,
            self.field_path,
        )


def read_queue_sources() -> set[str]:
    if not QUEUE_PATH.exists():
        return set()
    with QUEUE_PATH.open("r", encoding="utf-8", newline="") as handle:
        return {row["source"] for row in csv.DictReader(handle, delimiter="\t")}


def read_dictionary_sources() -> set[str]:
    if not DICTIONARY_PATH.exists():
        return set()
    sources: set[str] = set()
    with DICTIONARY_PATH.open("r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.rstrip("\n")
            if not line or line.startswith("#") or "=" not in line:
                continue
            source, _translation = line.split("=", 1)
            sources.add(unescape_xunity(source))
    return sources


def unescape_xunity(text: str) -> str:
    return text.replace("\\n", "\n").replace("\\r", "\r").replace("\\\\", "\\")


def known_variants(text: str) -> set[str]:
    variants = {text}
    queue = [text]
    substitutions = [
        ("...", "…"),
        ("…", "..."),
        ("'", "’"),
        ("’", "'"),
        ("\n", "<br>"),
        ("<br>", "\n"),
        ("  ", " "),
    ]
    while queue:
        current = queue.pop()
        for old, new in substitutions:
            if old in current:
                candidate = current.replace(old, new)
                if candidate not in variants:
                    variants.add(candidate)
                    queue.append(candidate)
    return variants


KNOWN_VARIANTS_BY_SOURCE = {source: known_variants(source) for source in KNOWN_STRINGS}
ALL_KNOWN_VARIANTS = set().union(*KNOWN_VARIANTS_BY_SOURCE.values())


def matches_known(text: str) -> list[str]:
    text_fold = text.casefold()
    hits: list[str] = []
    for original, variants in KNOWN_VARIANTS_BY_SOURCE.items():
        for variant in variants:
            variant_fold = variant.casefold()
            if len(variant.strip()) <= 5:
                pattern = rf"(?<![A-Za-z]){re.escape(variant)}(?![A-Za-z])"
                if not re.search(pattern, text, flags=re.IGNORECASE):
                    continue
            elif variant in text or variant_fold in text_fold:
                pass
            else:
                continue
            if variant:
                hits.append(original)
                break
    return hits


def iter_length_prefixed_utf8(data: bytes, max_len: int = 100_000) -> Iterable[tuple[int, str]]:
    limit = len(data) - 4
    for offset in range(max(0, limit)):
        (length,) = struct.unpack_from("<I", data, offset)
        if length <= 0 or length > max_len or offset + 4 + length > len(data):
            continue
        payload = data[offset + 4 : offset + 4 + length]
        try:
            text = payload.decode("utf-8")
        except UnicodeDecodeError:
            continue
        if is_probable_text(text):
            yield offset + 4, text


def is_probable_text(text: str) -> bool:
    if not text or "\x00" in text:
        return False
    printable = sum(1 for ch in text if ch.isprintable() or ch in "\r\n\t")
    return printable / max(len(text), 1) > 0.95


def raw_known_hits(asset_file: str, data: bytes) -> list[Finding]:
    findings: list[Finding] = []
    for known, variants in KNOWN_VARIANTS_BY_SOURCE.items():
        for variant in sorted(variants, key=len, reverse=True):
            if variant != variant.strip():
                continue
            for encoding, payload in (
                ("utf-8", variant.encode("utf-8", errors="ignore")),
                ("utf-16le", variant.encode("utf-16le", errors="ignore")),
            ):
                if not payload:
                    continue
                start = 0
                while True:
                    offset = data.find(payload, start)
                    if offset == -1:
                        break
                    findings.append(
                        Finding(
                            source=variant,
                            asset_file=asset_file,
                            object_type="raw_bytes",
                            object_name="",
                            path_id="",
                            field_path="known_string_search",
                            offset_or_location=f"byte {offset} ({encoding})",
                            confidence="medium",
                            notes=f"known-string raw hit for {known!r}",
                        )
                    )
                    start = offset + max(len(payload), 1)
    return findings


def safe_read_name(obj: Any) -> str:
    try:
        data = obj.read()
    except Exception:
        return ""
    return str(getattr(data, "m_Name", "") or "")


def make_object_index(env: Any) -> tuple[dict[int, Any], list[Any], dict[int, str]]:
    objects = list(env.objects)
    by_id = {int(obj.path_id): obj for obj in objects}
    names = {int(obj.path_id): safe_read_name(obj) for obj in objects}
    return by_id, objects, names


def owning_objects(objects: list[Any], offset: int) -> list[Any]:
    return [
        obj
        for obj in objects
        if getattr(obj, "byte_start", -1) <= offset < getattr(obj, "byte_start", -1) + getattr(obj, "byte_size", 0)
    ]


def monobehaviour_game_object_name(raw: bytes, names: dict[int, str]) -> str:
    if len(raw) < 8:
        return ""
    try:
        (_file_id, path_id) = struct.unpack_from("<ii", raw, 0)
    except struct.error:
        return ""
    return names.get(path_id, "")


def scan_textasset_csv(asset_file: str, obj: Any, object_name: str, script: str) -> list[Finding]:
    findings: list[Finding] = []
    if object_name not in {"journals", "dialogues"}:
        return findings
    text = script.lstrip("\ufeff")
    rows = list(csv.DictReader(text.splitlines(), delimiter=";", quotechar='"'))
    field_names = {"journals": {"text", "title"}, "dialogues": {"MAN", "WOMAN", "WHO"}}[object_name]
    id_field = "id" if object_name == "journals" else "ID"
    for line_number, row in enumerate(rows, start=2):
        row_id = row.get(id_field, "")
        for field_name in field_names:
            value = row.get(field_name, "")
            if not value or not value.strip():
                continue
            findings.append(
                Finding(
                    source=value,
                    asset_file=asset_file,
                    object_type="TextAsset",
                    object_name=object_name,
                    path_id=str(obj.path_id),
                    field_path=f"m_Script[{row_id}].{field_name}",
                    offset_or_location=f"csv row {line_number}",
                    confidence="high",
                    notes="player-facing TextAsset CSV payload",
                )
            )
    return findings


def scan_typetree_strings(
    asset_file: str, obj: Any, object_name: str, dictionary_sources: set[str]
) -> list[Finding]:
    try:
        tree = obj.read_typetree()
    except Exception:
        return []
    findings: list[Finding] = []

    def walk(value: Any, path: str) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                walk(child, f"{path}.{key}" if path else str(key))
        elif isinstance(value, list):
            for index, child in enumerate(value):
                walk(child, f"{path}[{index}]")
        elif isinstance(value, str) and value:
            if obj.type.name == "TextAsset" and object_name in {"journals", "dialogues"} and path == "m_Script":
                return
            known = matches_known(value)
            if known:
                findings.append(
                    Finding(
                        source=value,
                        asset_file=asset_file,
                        object_type=obj.type.name,
                        object_name=object_name,
                        path_id=str(obj.path_id),
                        field_path=path,
                        offset_or_location="typetree",
                        confidence="high" if value in dictionary_sources or known else "medium",
                        notes="UnityPy typetree known-string hit",
                    )
                )

    walk(tree, "")
    return findings


def scan_unity_asset(asset_file: str, data: bytes, dictionary_sources: set[str]) -> tuple[list[Finding], Counter[str]]:
    if UnityPy is None or asset_file.endswith(".resource"):
        return [], Counter()
    path = DATA_DIR / asset_file
    findings: list[Finding] = []
    counters: Counter[str] = Counter()
    try:
        env = UnityPy.load(str(path))
    except Exception as exc:
        counters[f"unity_load_failed:{type(exc).__name__}"] += 1
        return findings, counters

    _by_id, objects, names = make_object_index(env)
    counters["unity_objects"] = len(objects)
    for obj in objects:
        counters[f"type:{obj.type.name}"] += 1

    for obj in objects:
        object_name = names.get(int(obj.path_id), "")
        if obj.type.name == "TextAsset":
            try:
                data_obj = obj.read()
                script = str(getattr(data_obj, "m_Script", "") or "")
            except Exception:
                script = ""
            findings.extend(scan_textasset_csv(asset_file, obj, object_name, script))
        findings.extend(scan_typetree_strings(asset_file, obj, object_name, dictionary_sources))

        if obj.type.name == "MonoBehaviour":
            raw = obj.get_raw_data()
            go_name = monobehaviour_game_object_name(raw, names)
            for local_offset, text in iter_length_prefixed_utf8(raw, max_len=2000):
                if not matches_known(text):
                    continue
                confidence = "high" if go_name and go_name not in {"", text} else "medium"
                notes = "length-prefixed MonoBehaviour string"
                if go_name:
                    notes += f"; owning GameObject {go_name!r}"
                findings.append(
                    Finding(
                        source=text,
                        asset_file=asset_file,
                        object_type="MonoBehaviour",
                        object_name=go_name or object_name,
                        path_id=str(obj.path_id),
                        field_path="raw_length_prefixed_string",
                        offset_or_location=f"byte {obj.byte_start + local_offset}",
                        confidence=confidence,
                        notes=notes,
                    )
                )

    for finding in raw_known_hits(asset_file, data):
        try:
            raw_offset = int(finding.offset_or_location.split()[1])
        except Exception:
            raw_offset = -1
        owners = owning_objects(objects, raw_offset) if raw_offset >= 0 else []
        if owners:
            owner = owners[0]
            owner_name = names.get(int(owner.path_id), "")
            finding.object_type = owner.type.name
            finding.object_name = owner_name
            finding.path_id = str(owner.path_id)
            finding.notes += f"; raw hit falls inside Unity object {owner.path_id}"
        findings.append(finding)

    return findings, counters


def unique_findings(findings: Iterable[Finding]) -> list[Finding]:
    seen: set[tuple[str, str, str, str, str]] = set()
    result: list[Finding] = []
    for finding in findings:
        key = finding.key()
        if key in seen:
            continue
        seen.add(key)
        result.append(finding)
    return result


def write_tsv(findings: list[Finding]) -> None:
    OUT_TSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_TSV.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_COLUMNS, delimiter="\t")
        writer.writeheader()
        for finding in findings:
            writer.writerow(finding.__dict__)


def summarize_known(findings: list[Finding], dictionary_sources: set[str], queue_sources: set[str]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for known in KNOWN_STRINGS:
        matched_sources = sorted(
            {
                finding.source
                for finding in findings
                if known in matches_known(finding.source)
                or any(variant in finding.source for variant in KNOWN_VARIANTS_BY_SOURCE[known])
            }
        )
        rows.append(
            {
                "known": known,
                "found": "yes" if matched_sources else "no",
                "examples": " | ".join(repr(source[:120]) for source in matched_sources[:3]),
                "exact_in_queue": "yes" if known in queue_sources else "no",
                "exact_in_dictionary": "yes" if known in dictionary_sources else "no",
            }
        )
    return rows


def write_markdown(
    findings: list[Finding],
    counters_by_asset: dict[str, Counter[str]],
    dictionary_sources: set[str],
    queue_sources: set[str],
) -> None:
    OUT_DOC.parent.mkdir(parents=True, exist_ok=True)
    by_asset = Counter(finding.asset_file for finding in findings)
    by_type = Counter(finding.object_type for finding in findings)
    textasset_rows = [
        finding
        for finding in findings
        if finding.asset_file == "resources.assets"
        and finding.object_type == "TextAsset"
        and finding.object_name in {"journals", "dialogues"}
    ]
    unique_textasset_sources = {finding.source for finding in textasset_rows}
    missing_textasset_sources = sorted(unique_textasset_sources - queue_sources)
    covered_textasset_sources = sorted(unique_textasset_sources & dictionary_sources)
    tmp_end_day = [
        finding
        for finding in findings
        if finding.source == "End Day" and finding.asset_file.startswith("level")
    ]
    hook_warning = ""
    if LOG_PATH.exists():
        log_text = LOG_PATH.read_text(encoding="utf-8", errors="replace")
        if "TMP_Text_SetCharArray_Hook3" in log_text:
            hook_warning = "present"
        else:
            hook_warning = "not found"

    config_lines: list[str] = []
    if CONFIG_PATH.exists():
        config_text = CONFIG_PATH.read_text(encoding="utf-8", errors="replace")
        for key in [
            "GeneratePartialTranslations",
            "OutputUntranslatableText",
            "IgnoreVirtualTextSetterCallingRules",
            "TextGetterCompatibilityMode",
            "EnableTextPathLogging",
        ]:
            match = re.search(rf"^{re.escape(key)}=(.*)$", config_text, flags=re.MULTILINE)
            if match:
                config_lines.append(f"- `{key}={match.group(1).strip()}`")

    with OUT_DOC.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# resources.assets investigation\n\n")
        handle.write("Generated by `python scripts/scan_resources_assets.py`.\n\n")
        handle.write("## Environment\n\n")
        handle.write(f"- UnityPy available: `{'yes' if UnityPy is not None else 'no'}`\n")
        if UnityPy is not None:
            handle.write(f"- UnityPy version: `{getattr(UnityPy, '__version__', 'unknown')}`\n")
        handle.write(f"- XUnity `TMP_Text_SetCharArray_Hook3` warning in runtime log: `{hook_warning or 'log missing'}`\n")
        if config_lines:
            handle.write("- Test config settings:\n")
            handle.write("\n".join(config_lines))
            handle.write("\n")
        handle.write("\n## Summary\n\n")
        handle.write(f"- Total exported findings: `{len(findings)}`\n")
        handle.write(f"- Findings by asset: `{dict(sorted(by_asset.items()))}`\n")
        handle.write(f"- Findings by object type: `{dict(sorted(by_type.items()))}`\n")
        handle.write(
            f"- `resources.assets` TextAsset player-facing values exported from `journals` and `dialogues`: "
            f"`{len(textasset_rows)}` rows, `{len(unique_textasset_sources)}` unique strings.\n"
        )
        handle.write(
            f"- TextAsset strings missing from `translations/source_queue.tsv`: "
            f"`{len(missing_textasset_sources)}` unique strings.\n"
        )
        handle.write(
            f"- TextAsset strings already present in the generated XUnity dictionary: "
            f"`{len(covered_textasset_sources)}` unique strings.\n"
        )
        handle.write("- `resources.resource` did not load as a Unity serialized file; it was checked by raw byte search.\n")
        handle.write("\n")
        handle.write("## Storage Findings\n\n")
        handle.write(
            "- `resources.assets` contains normal `TextAsset` payloads named `journals` and `dialogues`. "
            "UnityPy reads their `m_Script` strings directly, so earlier empty-TextAsset conclusions are misleading for these two assets.\n"
        )
        handle.write(
            "- The `journals` TextAsset is semicolon-delimited data with `id`, `text`, `title`, and `chars` columns. "
            "The `dialogues` TextAsset is semicolon-delimited data with `ID`, `MAN`, `WOMAN`, and `WHO` columns.\n"
        )
        handle.write(
            "- Level comparison finds `End Day`, `Close Journal`, `I feel healthy!`, and related UI strings in length-prefixed "
            "MonoBehaviour data in `level3`. UnityPy cannot decode these MonoBehaviour typetrees here, but raw offsets fall inside "
            "Unity MonoBehaviour object ranges and often resolve to owning GameObjects such as `Text (TMP)`.\n"
        )
        handle.write(
            "- Object names such as `TalkDialog`, `doTask_friendTalk`, and `Canvas_Happy` are recorded only as context. "
            "They are not treated as visible text unless a separate serialized string field is found.\n"
        )
        if tmp_end_day:
            preferred_end_day = sorted(
                tmp_end_day,
                key=lambda finding: (finding.confidence != "high", not finding.object_name),
            )
            examples = ", ".join(
                f"`{finding.asset_file}` path `{finding.path_id}` object `{finding.object_name}` at {finding.offset_or_location}"
                for finding in preferred_end_day[:3]
            )
            handle.write(
                f"- `End Day` was found as a level MonoBehaviour string, not as a Texture2D/Sprite payload. Examples: {examples}.\n"
            )
        handle.write(
            "- `resources.resource` produced only an isolated raw `Row` hit in this known-string pass. "
            "No CSV, TextAsset, dialogue, journal, HUD, TMP, or other structured text payload was identified there.\n"
        )
        handle.write("\n## TextAsset Dictionary Coverage\n\n")
        if covered_textasset_sources:
            handle.write("Exact `journals`/`dialogues` TextAsset cells currently present in the dictionary include:\n\n")
            for source in covered_textasset_sources[:12]:
                preview = source.replace("\n", "\\n")
                if len(preview) > 180:
                    preview = preview[:177] + "..."
                handle.write(f"- `{preview}`\n")
        else:
            handle.write("No exact `journals`/`dialogues` TextAsset cells are currently present in the dictionary.\n")
        handle.write("\n## Known String Matrix\n\n")
        handle.write("| Known string | Found in inspected assets | Exact in queue | Exact in dictionary | Examples |\n")
        handle.write("| --- | --- | --- | --- | --- |\n")
        for row in summarize_known(findings, dictionary_sources, queue_sources):
            handle.write(
                f"| `{row['known']}` | {row['found']} | {row['exact_in_queue']} | "
                f"{row['exact_in_dictionary']} | {row['examples']} |\n"
            )
        handle.write("\n## Interpretation\n\n")
        handle.write(
            "- The remaining English dialogue is not explained solely by missing `resources.assets`: the exact straight-punctuation "
            "manual variants are already in the dictionary, but the TextAsset source uses ellipses/curly apostrophes for several "
            "lines. Exact TextAsset variants should be added for observed dialogue before treating every case as a hook failure.\n"
        )
        handle.write(
            "- If an exact TextAsset source string is present in the final dictionary and still renders in English, the likely cause "
            "is a runtime hook limitation, consistent with the `TMP_Text_SetCharArray_Hook3` warning and possible Febucci/custom "
            "typewriter text flow.\n"
        )
        handle.write(
            "- `I'm tired a bit` was not found in `resources.assets`, `resources.resource`, or the level files by this scan. "
            "Because it is already in the dictionary, a persistent English status message is more likely generated from code or "
            "assigned through an unhooked setter/variant than missing from the TextAssets.\n"
        )
        handle.write(
            "- `End Day` is a serialized `level3` MonoBehaviour string and also exists in the dictionary. If it remains English after "
            "a full restart with the current dictionary, classify it as unhooked runtime/TMP text, not texture replacement work.\n"
        )
        handle.write("\n## Asset Counters\n\n")
        for asset_file, counter in sorted(counters_by_asset.items()):
            handle.write(f"### {asset_file}\n\n")
            for key, value in sorted(counter.items()):
                handle.write(f"- `{key}`: `{value}`\n")
            handle.write("\n")
        handle.write("## Output\n\n")
        handle.write(f"- TSV export: `{OUT_TSV.relative_to(PROJECT_ROOT)}`\n")


def main() -> None:
    queue_sources = read_queue_sources()
    dictionary_sources = read_dictionary_sources()
    all_findings: list[Finding] = []
    counters_by_asset: dict[str, Counter[str]] = defaultdict(Counter)

    for asset_file in ASSET_FILES:
        path = DATA_DIR / asset_file
        if not path.exists():
            counters_by_asset[asset_file]["missing_file"] += 1
            continue
        data = path.read_bytes()
        counters_by_asset[asset_file]["bytes"] = len(data)
        raw_findings = raw_known_hits(asset_file, data)
        all_findings.extend(raw_findings)
        counters_by_asset[asset_file]["raw_known_hits"] = len(raw_findings)
        unity_findings, unity_counters = scan_unity_asset(asset_file, data, dictionary_sources)
        all_findings.extend(unity_findings)
        counters_by_asset[asset_file].update(unity_counters)

    findings = unique_findings(all_findings)
    findings.sort(key=lambda item: (item.asset_file, item.object_type, item.object_name, item.path_id, item.field_path, item.source))
    write_tsv(findings)
    write_markdown(findings, counters_by_asset, dictionary_sources, queue_sources)

    print(f"wrote {len(findings)} findings to {OUT_TSV.relative_to(PROJECT_ROOT)}")
    print(f"wrote findings report to {OUT_DOC.relative_to(PROJECT_ROOT)}")
    if UnityPy is None:
        print("warning: UnityPy is not installed for this interpreter; Unity-aware scanning was skipped")


if __name__ == "__main__":
    main()
