#!/usr/bin/env python3
"""Scan static game files for string clusters around known untranslated seeds."""

from __future__ import annotations

import csv
import re
from bisect import bisect_left, bisect_right
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "game_original/DontSleepWithTheFishes_Data"
QUEUE = ROOT / "translations/source_queue.tsv"
DICTIONARY = ROOT / "patches/xunity_autotranslator/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"
OUT = ROOT / "extracted/static_string_cluster_report.tsv"

FILES = [
    DATA / "level1",
    DATA / "level2",
    DATA / "level3",
    DATA / "level4",
    DATA / "level5",
    DATA / "resources.assets",
    DATA / "resources.resource",
    DATA / "il2cpp_data/Metadata/global-metadata.dat",
    ROOT / "game_original/GameAssembly.dll",
]

SEEDS = [
    "I'm hungry",
    "Satisfied",
    "Stomach's growling",
    "I'm well rested",
    "I still have energy",
    "I'm tired a bit",
    "Bored",
    "Peckish",
    "Unwell",
    "Happy",
    "Which way?",
    "Left",
    "Right",
    "Reach for it?",
    "Let Row handle it!",
    "What are you going to do?",
    "Get the Crate!",
    "Weight:",
    "kg",
    "Resume",
    "Settings",
    "Instant Clicking",
]

FIELDS = [
    "seed",
    "found_string",
    "file",
    "encoding_method",
    "byte_offset",
    "nearby_strings",
    "in_source_queue",
    "in_generated_dictionary",
    "recommended_action",
]

ASCII_RE = re.compile(rb"[ -~]{2,220}")
UTF16_RE = re.compile(rb"(?:[\x20-\x7e]\x00){2,220}")


def load_queue_sources() -> set[str]:
    with QUEUE.open("r", encoding="utf-8", newline="") as handle:
        return {row["source"] for row in csv.DictReader(handle, delimiter="\t")}


def unescape_xunity(text: str) -> str:
    return text.replace("\\n", "\n").replace("\\r", "\r").replace("\\\\", "\\")


def load_dictionary_sources() -> set[str]:
    sources: set[str] = set()
    if not DICTIONARY.exists():
        return sources
    with DICTIONARY.open("r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.rstrip("\n")
            if not line or line.startswith("#") or "=" not in line:
                continue
            sources.add(unescape_xunity(line.split("=", 1)[0]))
    return sources


def normalize(text: str) -> str:
    text = text.replace("’", "'").replace("…", "...")
    text = re.sub(r"<[^>]+>", "", text)
    return re.sub(r"\s+", " ", text).strip().casefold()


def seed_variants(seed: str) -> set[str]:
    variants = {seed, seed.replace("'", "’"), seed.replace("’", "'")}
    variants |= {item.replace("...", "…") for item in list(variants)}
    variants |= {item.replace("…", "...") for item in list(variants)}
    return variants


def decode_ascii(raw: bytes) -> str:
    return raw.decode("utf-8", errors="replace")


def decode_utf16(raw: bytes) -> str:
    return raw.decode("utf-16le", errors="replace")


def iter_strings(data: bytes) -> list[tuple[int, str, str]]:
    strings: list[tuple[int, str, str]] = []
    for match in ASCII_RE.finditer(data):
        strings.append((match.start(), "ascii_strings", decode_ascii(match.group(0))))
    for match in UTF16_RE.finditer(data):
        strings.append((match.start(), "utf16le_strings", decode_utf16(match.group(0))))
    strings.sort(key=lambda item: item[0])
    return strings


def nearby_for(
    strings: list[tuple[int, str, str]],
    offsets: list[int],
    offset: int,
    window: int = 5000,
) -> str:
    nearby: list[str] = []
    start = bisect_left(offsets, offset - window)
    end = bisect_right(offsets, offset + window)
    for other_offset, method, text in strings[start:end]:
        if abs(other_offset - offset) > window:
            continue
        cleaned = re.sub(r"\s+", " ", text).strip()
        if cleaned and cleaned not in nearby:
            nearby.append(cleaned)
        if len(nearby) >= 18:
            break
    return " | ".join(nearby)


def recommended_action(found: str, seed: str, in_queue: bool, in_dict: bool) -> str:
    if in_queue and in_dict:
        if seed in {"Weight:", "kg"}:
            return "covered_static_template; runtime_dynamic_capture_still_needed"
        return "already_covered"
    if in_queue:
        return "in_queue_rebuild_or_validate"
    if seed in {"kg"}:
        return "review_only_do_not_add_bare_unit_without_runtime_source"
    return "add_or_update_exact_source_if_player_facing"


def matches_seed(text: str, text_norm: str, seed: str, variants: list[str]) -> bool:
    if seed == "kg":
        return text.strip() == "kg" or "weight:" in text_norm or re.search(r"\d+(?:\.\d+)?kg\b", text)
    if seed in {"Left", "Right"}:
        return any(re.search(rf"(?<![A-Za-z]){re.escape(variant)}(?![A-Za-z])", text, re.IGNORECASE) for variant in seed_variants(seed))
    if seed == "Settings":
        return text.strip() == "Settings" or text.startswith("SettingsPanel_")
    if seed == "Satisfied":
        return text.strip() == "Satisfied" or text.strip() in {"I'm satisfied", "I am satisfied"}
    return any(variant in text_norm for variant in variants)


def main() -> int:
    queue_sources = load_queue_sources()
    dict_sources = load_dictionary_sources()
    report_rows: list[dict[str, str]] = []
    normalized_seed_variants = {seed: [normalize(item) for item in seed_variants(seed)] for seed in SEEDS}

    for path in FILES:
        if not path.exists():
            continue
        data = path.read_bytes()
        strings = iter_strings(data)
        offsets = [offset for offset, _method, _text in strings]
        normalized_strings = [(offset, method, text, normalize(text)) for offset, method, text in strings]
        seed_hits: dict[str, int] = defaultdict(int)
        for offset, method, text, text_norm in normalized_strings:
            if not text_norm:
                continue
            for seed in SEEDS:
                if seed_hits[seed] >= 300:
                    continue
                variants = normalized_seed_variants[seed]
                if not matches_seed(text, text_norm, seed, variants):
                    continue
                seed_hits[seed] += 1
                in_queue = text in queue_sources
                in_dict = text in dict_sources
                report_rows.append(
                    {
                        "seed": seed,
                        "found_string": text,
                        "file": str(path.relative_to(ROOT)),
                        "encoding_method": method,
                        "byte_offset": str(offset),
                        "nearby_strings": nearby_for(strings, offsets, offset),
                        "in_source_queue": "yes" if in_queue else "no",
                        "in_generated_dictionary": "yes" if in_dict else "no",
                        "recommended_action": recommended_action(text, seed, in_queue, in_dict),
                    }
                )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        writer.writerows(report_rows)

    print(f"wrote {len(report_rows)} static cluster rows to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
