#!/usr/bin/env python3
"""Validate source queue and generated XUnity.AutoTranslator dictionary."""

from __future__ import annotations

import argparse
import csv
import re
from collections import Counter
from pathlib import Path


DEFAULT_QUEUE = Path("translations/source_queue.tsv")
DEFAULT_DICT = Path(
    "patches/xunity_autotranslator/BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"
)

TAG_RE = re.compile(r"<[^>]+>")
PLACEHOLDER_RE = re.compile(r"(\{\d+\}|%[sd])")
DEBUG_PATTERNS = (
    "itemgive-itemid",
    "itemremove-itemid",
    "itembreak-itemid",
    "itemfix-itemid",
    "kill\\ngetfish\\nsuperhelp",
    "addhappen",
    "dangerset",
)


def escape_xunity(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\r", "\\r").replace("\n", "\\n")


def load_queue(queue: Path) -> list[dict[str, str]]:
    with queue.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        required = {
            "source",
            "context",
            "file",
            "kind",
            "machine_russian",
            "final_russian",
            "status",
            "notes",
        }
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise SystemExit(f"{queue} missing required columns: {sorted(missing)}")
        return list(reader)


def has_accidental_outer_whitespace(text: str) -> bool:
    if not text:
        return False
    comparable = text[:-1] if text.endswith("\r") else text
    return comparable != comparable.strip(" \t\n")


def validate_queue(rows: list[dict[str, str]]) -> list[str]:
    errors: list[str] = []
    sources = [row["source"] for row in rows]
    for source, count in Counter(sources).items():
        if count > 1:
            errors.append(f"duplicate source key in queue: {source!r}")

    for row in rows:
        source = row["source"]
        final = row["final_russian"]
        status = row["status"]
        if not source:
            errors.append("empty source key in queue")
            continue
        if status != "skip" and not final:
            errors.append(f"empty translation for player-facing row: {source!r}")
        if status != "skip" and (
            has_accidental_outer_whitespace(source) or has_accidental_outer_whitespace(final)
        ):
            errors.append(f"accidental outer whitespace: {source!r}")
        if status != "skip":
            source_tags = TAG_RE.findall(source)
            final_tags = TAG_RE.findall(final)
            missing_tags = [tag for tag in source_tags if tag not in final_tags]
            if missing_tags:
                errors.append(f"missing rich text tags for {source!r}: {missing_tags}")
            source_ph = PLACEHOLDER_RE.findall(source)
            final_ph = PLACEHOLDER_RE.findall(final)
            if Counter(source_ph) != Counter(final_ph):
                errors.append(f"placeholder mismatch for {source!r}: {source_ph} != {final_ph}")
            if "\\n" in source or "\\r" in source:
                errors.append(f"source queue contains literal backslash newline escape, should be real newline: {source!r}")
    return errors


def parse_dictionary_lines(path: Path) -> list[tuple[int, str, str]]:
    lines: list[tuple[int, str, str]] = []
    with path.open("r", encoding="utf-8") as handle:
        for lineno, raw in enumerate(handle, 1):
            line = raw.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                raise ValueError(f"line {lineno} lacks '=' separator")
            # Rich text tags contain '=', so split by known generated queue keys later.
            lines.append((lineno, line, ""))
    return lines


def validate_dictionary(path: Path, rows: list[dict[str, str]]) -> list[str]:
    errors: list[str] = []
    active_sources = [row["source"] for row in rows if row["status"] != "skip" and row["final_russian"]]
    escaped_to_source = {escape_xunity(source): source for source in active_sources}
    sorted_escaped = sorted(escaped_to_source, key=len, reverse=True)
    seen: set[str] = set()

    for lineno, line, _ in parse_dictionary_lines(path):
        matched_source = None
        matched_prefix = None
        for escaped in sorted_escaped:
            prefix = f"{escaped}="
            if line.startswith(prefix):
                matched_source = escaped_to_source[escaped]
                matched_prefix = prefix
                break
        if matched_source is None or matched_prefix is None:
            errors.append(f"line {lineno} does not match an active source key")
            continue
        if matched_source in seen:
            errors.append(f"duplicate source key in dictionary: {matched_source!r}")
        seen.add(matched_source)
        translation = line[len(matched_prefix) :]
        if not translation:
            errors.append(f"empty dictionary translation at line {lineno}")
        # Matching against queue-derived keys already catches accidental quote wrapping:
        # a wrapped key would not match unless the source itself visibly contains quotes.
        if any(pattern in line for pattern in DEBUG_PATTERNS):
            errors.append(f"debug command block leaked into dictionary at line {lineno}")
        if "\r" in line:
            errors.append(f"raw carriage return leaked into dictionary at line {lineno}")
        if "\\r" in line and "\\r\\n" not in line:
            # A lone escaped CR is allowed only if the source really had a lone CR.
            source_has_lone_cr = "\r" in matched_source and "\r\n" not in matched_source
            if not source_has_lone_cr:
                errors.append(f"suspicious broken escaped CR at line {lineno}")

    expected = set(active_sources)
    missing = expected - seen
    if missing:
        errors.append(f"dictionary missing {len(missing)} active source keys")
    return errors


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--queue", default=str(DEFAULT_QUEUE))
    parser.add_argument("--dictionary", default=str(DEFAULT_DICT))
    args = parser.parse_args()

    queue = Path(args.queue)
    dictionary = Path(args.dictionary)
    rows = load_queue(queue)
    errors = validate_queue(rows)
    errors.extend(validate_dictionary(dictionary, rows))
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        raise SystemExit(1)

    active = sum(1 for row in rows if row["status"] != "skip" and row["final_russian"])
    review = sum(1 for row in rows if row["status"] == "needs_review")
    skip = sum(1 for row in rows if row["status"] == "skip")
    print(f"validation ok: {active} active translations, {review} needs_review, {skip} skip")


if __name__ == "__main__":
    main()
